/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Bashekim;
import com.irem.models.Doktor;
import com.irem.models.Hasta;
import com.irem.models.Resepsiyonist;
import com.irem.veritabani.VeriTabaniBaglanti;
import com.irem.veritabani.YardimciMethotlar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.irem.models.Yoneticiler;

/**
 *
 * @author İREM SAMUR
 */
public class AnaEkran extends javax.swing.JFrame {
    private VeriTabaniBaglanti conn = new VeriTabaniBaglanti();//Veritabanına bu classın bağlantısı sağlanır
    private long parola = 10000000+(int)(Math.random()* 90000000);
    private String geciciParola = String.valueOf(parola);
    Yoneticiler yonetici = new Yoneticiler();
    private String mesaj = "LIFE HASTANESİ BİLGİ SİSTEMİ\nAna Ekrana yönlendiriliyorsunuz...";
   

  
    

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
        tarihGoster();
        yonetici.setMesaj(mesaj);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tarih_etiketi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hastaTcNo_alani = new javax.swing.JTextField();
        hastaParola_alani = new javax.swing.JPasswordField();
        hastaGirisYap_butonu = new javax.swing.JButton();
        hastaKaydol_butonu = new javax.swing.JButton();
        sifremiUnuttum_butonu1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        doktorTc_alani = new javax.swing.JTextField();
        doktorParola_alani = new javax.swing.JPasswordField();
        doktorGirisYap_butonu = new javax.swing.JButton();
        mesaj_alani2 = new javax.swing.JLabel();
        sifremiUnuttum_butonu2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resTc_alani = new javax.swing.JTextField();
        resGiris_butonu = new javax.swing.JButton();
        resParola_alani = new javax.swing.JPasswordField();
        sifremiUnuttum_butonu3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        yoneticiTc_alani = new javax.swing.JTextField();
        yoneticiParola_alani = new javax.swing.JPasswordField();
        yoneticiGiris_butonu = new javax.swing.JButton();
        sifremiUnuttum_butonu4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANA EKRAN");

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\icon3_100x100.jpg")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("                            LIFE HASTANESİ BİLGİ SİSTEMİ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 4));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\icon2_100x100.jpg")); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));

        tarih_etiketi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tarih_etiketi.setForeground(new java.awt.Color(255, 0, 0));
        tarih_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(tarih_etiketi, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tarih_etiketi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 1330, 120);

        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("HASTANE BİLGİ SİSTEMİNE HOŞGELDİNİZ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 4));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(350, 40, 440, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\user_200x200.jpg")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 4));
        jPanel3.add(jLabel8);
        jLabel8.setBounds(120, 170, 200, 180);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jLabel12.setText("Tc Kimlik No");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel3.add(jLabel12);
        jLabel12.setBounds(420, 210, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 102));
        jLabel13.setText("     Parola");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel3.add(jLabel13);
        jLabel13.setBounds(420, 280, 100, 30);

        hastaTcNo_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaTcNo_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaTcNo_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 4));
        jPanel3.add(hastaTcNo_alani);
        hastaTcNo_alani.setBounds(610, 210, 140, 30);

        hastaParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 4));
        jPanel3.add(hastaParola_alani);
        hastaParola_alani.setBounds(610, 280, 140, 30);

        hastaGirisYap_butonu.setBackground(new java.awt.Color(102, 255, 102));
        hastaGirisYap_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaGirisYap_butonu.setForeground(new java.awt.Color(204, 0, 204));
        hastaGirisYap_butonu.setText("Giriş Yap");
        hastaGirisYap_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 4));
        hastaGirisYap_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaGirisYap_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(hastaGirisYap_butonu);
        hastaGirisYap_butonu.setBounds(270, 430, 130, 30);

        hastaKaydol_butonu.setBackground(new java.awt.Color(102, 255, 102));
        hastaKaydol_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaKaydol_butonu.setForeground(new java.awt.Color(204, 0, 255));
        hastaKaydol_butonu.setText("Kaydol");
        hastaKaydol_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 4));
        hastaKaydol_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaKaydol_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(hastaKaydol_butonu);
        hastaKaydol_butonu.setBounds(630, 430, 130, 30);

        sifremiUnuttum_butonu1.setBackground(new java.awt.Color(255, 255, 255));
        sifremiUnuttum_butonu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifremiUnuttum_butonu1.setForeground(new java.awt.Color(204, 0, 153));
        sifremiUnuttum_butonu1.setText("Şifremi Unuttum");
        sifremiUnuttum_butonu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 4));
        sifremiUnuttum_butonu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiUnuttum_butonu1ActionPerformed(evt);
            }
        });
        jPanel3.add(sifremiUnuttum_butonu1);
        sifremiUnuttum_butonu1.setBounds(460, 430, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\medical2_1400x700_1338x600.jpg")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 1310, 530);

        jTabbedPane1.addTab("Hasta Girişi", jPanel3);

        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("HASTANE BİLGİ SİSTEMİNE HOŞGELDİNİZ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 4));
        jPanel4.add(jLabel7);
        jLabel7.setBounds(390, 50, 450, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\doctors_200x200.jpg")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel4.add(jLabel9);
        jLabel9.setBounds(140, 180, 210, 200);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("   Tc Kimlik No");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel4.add(jLabel10);
        jLabel10.setBounds(470, 210, 130, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("          Şifre");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel4.add(jLabel11);
        jLabel11.setBounds(470, 300, 130, 50);

        doktorTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        doktorTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel4.add(doktorTc_alani);
        doktorTc_alani.setBounds(660, 210, 150, 50);

        doktorParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        doktorParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel4.add(doktorParola_alani);
        doktorParola_alani.setBounds(660, 300, 150, 50);

        doktorGirisYap_butonu.setBackground(new java.awt.Color(255, 255, 0));
        doktorGirisYap_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorGirisYap_butonu.setForeground(new java.awt.Color(255, 0, 102));
        doktorGirisYap_butonu.setText("Giriş Yap");
        doktorGirisYap_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 4));
        doktorGirisYap_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorGirisYap_butonuActionPerformed(evt);
            }
        });
        jPanel4.add(doktorGirisYap_butonu);
        doktorGirisYap_butonu.setBounds(370, 450, 140, 40);

        mesaj_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesaj_alani2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(mesaj_alani2);
        mesaj_alani2.setBounds(390, 380, 570, 40);

        sifremiUnuttum_butonu2.setBackground(new java.awt.Color(255, 102, 255));
        sifremiUnuttum_butonu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifremiUnuttum_butonu2.setForeground(new java.awt.Color(255, 0, 0));
        sifremiUnuttum_butonu2.setText("Şifremi Unuttum");
        sifremiUnuttum_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        sifremiUnuttum_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiUnuttum_butonu2ActionPerformed(evt);
            }
        });
        jPanel4.add(sifremiUnuttum_butonu2);
        sifremiUnuttum_butonu2.setBounds(560, 450, 150, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\medical2_1400x700_1338x600.jpg")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 4));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 0, 1310, 530);

        jTabbedPane1.addTab("Başhekim/Doktor Girişi", jPanel4);

        jPanel5.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("HASTANE BİLGİ SİSTEMİNE HOŞGELDİNİZ");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        jPanel5.add(jLabel15);
        jLabel15.setBounds(350, 70, 450, 70);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 153));
        jLabel16.setText("      Tc Kimlik No");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel5.add(jLabel16);
        jLabel16.setBounds(310, 230, 140, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 204));
        jLabel17.setText("          Parola");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel5.add(jLabel17);
        jLabel17.setBounds(310, 330, 140, 50);

        resTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        resTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153), 4));
        jPanel5.add(resTc_alani);
        resTc_alani.setBounds(620, 230, 160, 50);

        resGiris_butonu.setBackground(new java.awt.Color(255, 255, 0));
        resGiris_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resGiris_butonu.setForeground(new java.awt.Color(255, 0, 0));
        resGiris_butonu.setText("Giriş Yap");
        resGiris_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        resGiris_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resGiris_butonuActionPerformed(evt);
            }
        });
        jPanel5.add(resGiris_butonu);
        resGiris_butonu.setBounds(350, 440, 160, 40);

        resParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        resParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153), 4));
        jPanel5.add(resParola_alani);
        resParola_alani.setBounds(620, 330, 160, 50);

        sifremiUnuttum_butonu3.setBackground(new java.awt.Color(255, 255, 0));
        sifremiUnuttum_butonu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifremiUnuttum_butonu3.setForeground(new java.awt.Color(255, 0, 102));
        sifremiUnuttum_butonu3.setText("Şifremi Unuttum");
        sifremiUnuttum_butonu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        sifremiUnuttum_butonu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiUnuttum_butonu3ActionPerformed(evt);
            }
        });
        jPanel5.add(sifremiUnuttum_butonu3);
        sifremiUnuttum_butonu3.setBounds(613, 440, 140, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\hospitalReception_200x200.jpg")); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel5.add(jLabel22);
        jLabel22.setBounds(90, 220, 170, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\medical2_1400x700_1338x600.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 530);

        jTabbedPane1.addTab("Resepsiyonist Girişi", jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 255, 204));
        jPanel7.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("       HASTANE BİLGİ SİSTEMİNE HOŞGELDİNİZ");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        jPanel7.add(jLabel19);
        jLabel19.setBounds(300, 70, 510, 60);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 102));
        jLabel20.setText("       Tc Kimlik No");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel7.add(jLabel20);
        jLabel20.setBounds(280, 250, 160, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 102));
        jLabel21.setText("           Parola");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel7.add(jLabel21);
        jLabel21.setBounds(280, 360, 160, 50);

        yoneticiTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        yoneticiTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel7.add(yoneticiTc_alani);
        yoneticiTc_alani.setBounds(570, 250, 180, 50);

        yoneticiParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        yoneticiParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel7.add(yoneticiParola_alani);
        yoneticiParola_alani.setBounds(570, 360, 180, 50);

        yoneticiGiris_butonu.setBackground(new java.awt.Color(153, 255, 153));
        yoneticiGiris_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiGiris_butonu.setForeground(new java.awt.Color(255, 0, 0));
        yoneticiGiris_butonu.setText("Giriş Yap");
        yoneticiGiris_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        yoneticiGiris_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiGiris_butonuActionPerformed(evt);
            }
        });
        jPanel7.add(yoneticiGiris_butonu);
        yoneticiGiris_butonu.setBounds(310, 460, 170, 40);

        sifremiUnuttum_butonu4.setBackground(new java.awt.Color(153, 255, 255));
        sifremiUnuttum_butonu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sifremiUnuttum_butonu4.setForeground(new java.awt.Color(204, 0, 102));
        sifremiUnuttum_butonu4.setText("Şifremi Unuttum");
        sifremiUnuttum_butonu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        sifremiUnuttum_butonu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiUnuttum_butonu4ActionPerformed(evt);
            }
        });
        jPanel7.add(sifremiUnuttum_butonu4);
        sifremiUnuttum_butonu4.setBounds(560, 460, 150, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\managers2.jpeg")); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel7.add(jLabel23);
        jLabel23.setBounds(50, 240, 200, 170);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\medical2_1400x700_1338x600.jpg")); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel7.add(jLabel18);
        jLabel18.setBounds(0, 0, 1300, 530);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Yönetici Girişi", jPanel6);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 130, 1310, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tarihGoster(){
        //Şimdiki zaman tarihini gösterir
        
        SimpleDateFormat tarih=new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
        Date tarihSaat=new Date();
        tarih_etiketi.setText(tarih.format(tarihSaat));
        
        
        


    }
    private void doktorGirisYap_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorGirisYap_butonuActionPerformed
        // TODO add your handling code here:
        
           if(doktorTc_alani.getText().length()==0 || doktorParola_alani.getPassword().toString().length()==0){
            YardimciMethotlar.mesajGoster("dolu");//YardimciMethotlar classında bulunan static method çalıştırılıp hata mesajı verir.
            //Yani kullanıcının boş bıraktığı yerlere karşı uyarı mesajı verir
        }
        else{
            String tc = doktorTc_alani.getText();
            String password = new String(doktorParola_alani.getPassword());
            boolean kontrol = false;
            boolean durum1 = true;
            boolean durum2 = true;
            
            try {
                Connection con = conn.conDb();
                Statement st = con.createStatement();//Veritabanımı kullanıyorum.
                String sorgu = "SELECT * FROM user ";
                ResultSet rs = st.executeQuery(sorgu);
                while(rs.next()){
                    if(tc.equals(rs.getString("tcno"))&& password.equals(rs.getString("parola"))){
                        
                        if(rs.getString("kullanici_turu").equals("bashekim")){
                            Bashekim bhekim = new Bashekim();// Giriş yapan başhekim olur.
                            bhekim.setId(rs.getInt("id"));//Başhekim id değili veritabanından çektiği giriş yapan başhekim id sine eşit olur.
                            bhekim.setParola("parola");
                            bhekim.setTcno(rs.getString("tcno"));
                            bhekim.setAd(rs.getString("ad"));
                            bhekim.setSoyad(rs.getString("soyad"));
                            bhekim.setMail_adresi(rs.getString("mail_adresi"));
                            bhekim.setCeptel_no(rs.getString("ceptel_no"));
                            bhekim.setAdres(rs.getString("adres"));
                            bhekim.setCinsiyet(rs.getString("cinsiyet"));
                            bhekim.setUnvan(rs.getString("unvan"));
                            bhekim.setTur("kullanici_turu");//Giriş yapan başhekimin değerlerini tutuyor.
                            
                          //System.out.println(bhekim.getName());//Böylece giriş yapan başhekimin değerlerini Bashekim classı aracılığıyla tutmuş olur
                            BashekimEkrani bhekimEkrani = new BashekimEkrani(bhekim);
                            bhekimEkrani.setVisible(true);//Başhekim giriş ekranını açar
                            dispose();//Şuan içinde bulunduğumuz ekranı kapatır
                            durum1=false;
                            
                        }
                        if(rs.getString("kullanici_turu").equals("doktor")){
                            Doktor doktor1 = new Doktor();
                            doktor1.setId(rs.getInt("id"));//doktor classındaki  id değeri veritabanından çektiği giriş yapan başhekim id sine eşit olur.
                            doktor1.setParola("parola");
                            doktor1.setTcno(rs.getString("tcno"));
                            doktor1.setAd(rs.getString("ad"));
                            doktor1.setSoyad(rs.getString("soyad"));
                            doktor1.setMail_adresi(rs.getString("mail_adresi"));
                            doktor1.setCeptel_no(rs.getString("ceptel_no"));
                            doktor1.setAdres(rs.getString("adres"));
                            doktor1.setCinsiyet(rs.getString("cinsiyet"));
                            doktor1.setUnvan(rs.getString("unvan"));
                            doktor1.setTur("kullanici_turu");
                            
                            DoktorEkrani doktorEkran = new DoktorEkrani(doktor1);
                            doktorEkran.setVisible(true);
                            dispose();
                            durum2=false;
                            
                            
                        }
                    
                    }
                    
                    
                    
                    
                    
                }
               
                
            } catch (SQLException ex) {
               
                Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(durum1==true || durum2==true){
                mesaj_alani2.setText("Böyle bir kullanıcı bulunamadı !!\nParola veya Tc kimlik no yanlış veya böyle bir hesap bulunmamaktadır!!");
                
            }
            
        }
    }//GEN-LAST:event_doktorGirisYap_butonuActionPerformed

    private void hastaKaydol_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaKaydol_butonuActionPerformed
        // TODO add your handling code here:
        HastaKayitEkrani hastaKayitEkran = new HastaKayitEkrani();
        hastaKayitEkran.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_hastaKaydol_butonuActionPerformed

    private void hastaGirisYap_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaGirisYap_butonuActionPerformed
        // TODO add your handling code here:
        if(hastaTcNo_alani.getText().length()==0 || hastaParola_alani.getPassword().toString().length()==0  ){
            YardimciMethotlar.mesajGoster("dolu");
            
            
        }
        else{
            
            String tc = hastaTcNo_alani.getText();
            String password = new String(hastaParola_alani.getPassword());
            boolean key = true;
            
            try {
                Connection con = conn.conDb();
                Statement st = con.createStatement();//Veritabanımı kullanıyorum.
                String sorgu = "SELECT * FROM user ";
                ResultSet rs = st.executeQuery(sorgu);
                
                while(rs.next()){
                    if(tc.equals(rs.getString("tcno"))&& password.equals(rs.getString("parola"))){
                        
                        if(rs.getString("kullanici_turu").equals("hasta")){
                            Hasta hasta = new Hasta();// Giriş yapan hasta olur.
                            hasta.setId(rs.getInt("id"));//giriş yapan hasta id değeri veritabanından çektiği giriş yapan hasta id sine eşit olur.
                            hasta.setParola("parola");
                            hasta.setTcno(rs.getString("tcno"));
                            hasta.setAd(rs.getString("ad"));
                            hasta.setSoyad(rs.getString("soyad"));
                            hasta.setMail_adresi(rs.getString("mail_adresi"));
                            hasta.setCeptel_no(rs.getString("ceptel_no"));
                            hasta.setAdres(rs.getString("adres"));
                            hasta.setCinsiyet(rs.getString("cinsiyet"));
                            hasta.setDogumTarihi(rs.getString("dogumTarihi"));
                            hasta.setYas(rs.getString("hasta_yasi"));
                            
                            hasta.setTur("kullanici_turu");//Giriş yapan hasta değerlerini tutuyor.
                        //System.out.println(bhekim.getName());//Böylece giriş yapan hasta classı değerlerini, bilgilerini  Hasta classı aracılığıyla tutmuş olur
                            HastaIslemEkrani hastaEkrani = new HastaIslemEkrani(hasta);
                            hastaEkrani.setVisible(true);//hasta işlem ekranını açar
                            dispose();//Şuan içinde bulunduğumuz ekranı kapatır
                            key=false;
                            
                        }
                       
                    
                    }
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(key){
                YardimciMethotlar.mesajGoster("Böyle bir kullanıcı bulunamadı !!\nParola veya Tc kimlik no yanlış veya böyle bir hesap bulunmamaktadır!!");
                
                
            }
        }
    }//GEN-LAST:event_hastaGirisYap_butonuActionPerformed

    private void resGiris_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resGiris_butonuActionPerformed
        // TODO add your handling code here:
        
        if(resTc_alani.getText().length()==0 || resParola_alani.getPassword().toString().length()==0  ){
            YardimciMethotlar.mesajGoster("dolu");
            
            
        }
        else{
            
            String tc = resTc_alani.getText();
            String parola = new String(resParola_alani.getPassword());
            boolean key = true;
            
            try {
                Connection con = conn.conDb();
                Statement st = con.createStatement();//Veritabanımı kullanıyorum.
                String sorgu = "SELECT * FROM user ";
                ResultSet rs = st.executeQuery(sorgu);
                
                while(rs.next()){
                    if(tc.equals(rs.getString("tcno"))&& parola.equals(rs.getString("parola"))){
                       
                        if(rs.getString("kullanici_turu").equals("resepsiyonist")){
                            Resepsiyonist resepsiyonist = new Resepsiyonist();// Giriş yapan resepsiyonist olur.
                            resepsiyonist.setId(rs.getInt("id"));//giriş yapan resepsiyonist id değeri veritabanından çektiği giriş yapan resepsiyonist id sine eşit olur.
                            resepsiyonist.setParola("parola");
                            resepsiyonist.setTcno(rs.getString("tcno"));
                            resepsiyonist.setAd(rs.getString("ad"));
                            resepsiyonist.setSoyad(rs.getString("soyad"));
                            resepsiyonist.setMail_adresi(rs.getString("mail_adresi"));
                            resepsiyonist.setCeptel_no(rs.getString("ceptel_no"));
                            resepsiyonist.setAdres(rs.getString("adres"));
                            resepsiyonist.setCinsiyet(rs.getString("cinsiyet"));
                            resepsiyonist.setTur("kullanici_turu");//Giriş yapan resepsiyonist değerlerini tutuyor.
                        //System.out.println(bhekim.getName());//Böylece giriş yapan resepsiyonist değerlerini Resepsiyonist classı aracılığıyla tutmuş olur
                            ResepsiyonistEkrani resepsiyonistEkrani = new ResepsiyonistEkrani(resepsiyonist);
                            resepsiyonistEkrani.setVisible(true);//Resepsiyonist giriş ekranını açar
                            dispose();//Şuan içinde bulunduğumuz ekranı kapatır
                            key=false;
                            
                        }
                       
                    
                    }
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(key){
                YardimciMethotlar.mesajGoster("Böyle bir kullanıcı bulunamadı !!\nParola veya Tc kimlik no yanlış veya böyle bir hesap bulunmamaktadır!!");
                
                
            }
        }
        
    }//GEN-LAST:event_resGiris_butonuActionPerformed

    private void yoneticiGiris_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiGiris_butonuActionPerformed
        // TODO add your handling code here:
        if(yoneticiTc_alani.getText().length()==0 || yoneticiParola_alani.getPassword().toString().length()==0  ){
            YardimciMethotlar.mesajGoster("dolu");
            
            
        }
        else{
            
            String tc = yoneticiTc_alani.getText();
            String parola = new String(yoneticiParola_alani.getPassword());
            boolean key = true;
            
            try {
                Connection con = conn.conDb();
                Statement st = con.createStatement();//Veritabanımı kullanıyorum.
                String sorgu = "SELECT * FROM user ";
                ResultSet rs = st.executeQuery(sorgu);
                
                while(rs.next()){
                    if(tc.equals(rs.getString("tcno"))&& parola.equals(rs.getString("parola"))){
                       
                        if(rs.getString("kullanici_turu").equals("yonetici")){
                            Yoneticiler yonetici = new Yoneticiler();// Giriş yapan başhekim olur.
                            yonetici.setId(rs.getInt("id"));//Giriş yapan yönetici id değerini veritabanından çektiği giriş yapan yönetici id sine eşit olur.
                            yonetici.setParola("parola");
                            yonetici.setTcno(rs.getString("tcno"));
                            yonetici.setAd(rs.getString("ad"));
                            yonetici.setSoyad(rs.getString("soyad"));
                            yonetici.setMail_adresi(rs.getString("mail_adresi"));
                            yonetici.setCeptel_no(rs.getString("ceptel_no"));
                            yonetici.setAdres(rs.getString("adres"));
                            yonetici.setCinsiyet(rs.getString("cinsiyet"));
                            yonetici.setTur("kullanici_turu");//Giriş yapan yönetici değerlerini tutuyor.
                        //System.out.println(bhekim.getName());//Böylece giriş yapan yönetici değerlerini Yoneticiler classı aracılığıyla tutmuş olur
                            YoneticiAnaEkrani yoneticiEkrani = new YoneticiAnaEkrani(yonetici);
                            yoneticiEkrani.setVisible(true);//yönetici giriş ekranını açar
                            dispose();//Şuan içinde bulunduğumuz ekranı kapatır
                            key=false;
                            
                        }
                       
                    
                    }
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(key){
                YardimciMethotlar.mesajGoster("Böyle bir kullanıcı bulunamadı !!\nParola veya Tc kimlik no yanlış veya böyle bir hesap bulunmamaktadır!!");
                
                
            }
        }
        
        
    }//GEN-LAST:event_yoneticiGiris_butonuActionPerformed

    private void sifremiUnuttum_butonu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiUnuttum_butonu1ActionPerformed
        // TODO add your handling code here:
        String tc = String.valueOf(JOptionPane.showInputDialog("11 haneli tc kimlik numaranızı giriniz..."));
        
        Hasta hasta = new Hasta();
        boolean durum = hasta.hastaGeciciSifreDegisimi(tc, geciciParola);
        if(durum){
            YardimciMethotlar.mesajGoster(tc+" numaralı hesabınıza ait geçici parolanız "+geciciParola+" olarak atanmıştır.");
            YardimciMethotlar.mesajGoster("Bu geçici parolanız sisteme giriş yapabilirsiniz \n Güvenliğiniz için parolanızı değiştirmeyi unutmayınız!!");
           
        }
        else{
            YardimciMethotlar.mesajGoster("hata");
        }
       
    }//GEN-LAST:event_sifremiUnuttum_butonu1ActionPerformed

    private void sifremiUnuttum_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiUnuttum_butonu2ActionPerformed
        // TODO add your handling code here:
        //Kullanıcının şifresini unutması durumunda kullanıcının tc'sini ister.
        //Ve tc'ye göre kullanıcıya rastgele 8 haneli bir geçici şifre atar.
        //Ve kullanıcıdan bu şifre ile giriş yapması istenir
        String tc = String.valueOf(JOptionPane.showInputDialog("11 haneli tc kimlik numaranızı giriniz..."));
        
        Doktor doktor = new Doktor();
        boolean durum = doktor.doktorGeciciSifreDegisimi(tc, geciciParola);
        if(durum){
            YardimciMethotlar.mesajGoster(tc+" numaralı hesabınıza ait geçici parolanız "+geciciParola+" olarak atanmıştır.");
            YardimciMethotlar.mesajGoster("Bu geçici parolanız sisteme giriş yapabilirsiniz \n Güvenliğiniz için parolanızı değiştirmeyi unutmayınız!!");
           
        }
        else{
            YardimciMethotlar.mesajGoster("hata");
        }
        
    }//GEN-LAST:event_sifremiUnuttum_butonu2ActionPerformed

    private void sifremiUnuttum_butonu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiUnuttum_butonu3ActionPerformed
        // TODO add your handling code here:
             String tc = String.valueOf(JOptionPane.showInputDialog("11 haneli tc kimlik numaranızı giriniz..."));
        
            Resepsiyonist resepsiyonist = new Resepsiyonist();
            boolean durum = resepsiyonist.resepsiyonistGeciciSifreDegisimi(tc, geciciParola);
            if(durum){
                YardimciMethotlar.mesajGoster(tc+" numaralı hesabınıza ait geçici parolanız "+geciciParola+" olarak atanmıştır.");
                YardimciMethotlar.mesajGoster("Bu geçici parolanız sisteme giriş yapabilirsiniz \n Güvenliğiniz için parolanızı değiştirmeyi unutmayınız!!");
           
        }
            else{
                YardimciMethotlar.mesajGoster("hata");
        }
    }//GEN-LAST:event_sifremiUnuttum_butonu3ActionPerformed

    private void sifremiUnuttum_butonu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiUnuttum_butonu4ActionPerformed
        // TODO add your handling code here:
        
            String tc = String.valueOf(JOptionPane.showInputDialog("11 haneli tc kimlik numaranızı giriniz..."));
        
            Yoneticiler yoneticiler = new Yoneticiler();
            boolean durum = yoneticiler.yoneticiGeciciSifreDegisimi(tc, geciciParola);
            if(durum){
                YardimciMethotlar.mesajGoster(tc+" numaralı hesabınıza ait geçici parolanız "+geciciParola+" olarak atanmıştır.");
                YardimciMethotlar.mesajGoster("Bu geçici parolanız sisteme giriş yapabilirsiniz \n Güvenliğiniz için parolanızı değiştirmeyi unutmayınız!!");
           
        }
            else{
                YardimciMethotlar.mesajGoster("hata");
        }
    }//GEN-LAST:event_sifremiUnuttum_butonu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doktorGirisYap_butonu;
    private javax.swing.JPasswordField doktorParola_alani;
    private javax.swing.JTextField doktorTc_alani;
    private javax.swing.JButton hastaGirisYap_butonu;
    private javax.swing.JButton hastaKaydol_butonu;
    private javax.swing.JPasswordField hastaParola_alani;
    private javax.swing.JTextField hastaTcNo_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mesaj_alani2;
    private javax.swing.JButton resGiris_butonu;
    private javax.swing.JPasswordField resParola_alani;
    private javax.swing.JTextField resTc_alani;
    private javax.swing.JButton sifremiUnuttum_butonu1;
    private javax.swing.JButton sifremiUnuttum_butonu2;
    private javax.swing.JButton sifremiUnuttum_butonu3;
    private javax.swing.JButton sifremiUnuttum_butonu4;
    private javax.swing.JLabel tarih_etiketi;
    private javax.swing.JButton yoneticiGiris_butonu;
    private javax.swing.JPasswordField yoneticiParola_alani;
    private javax.swing.JTextField yoneticiTc_alani;
    // End of variables declaration//GEN-END:variables
}
