/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Bashekim;


/**
 *
 * @author İREM SAMUR
 */
public class BashekimBilgileriGoster extends javax.swing.JFrame {
    Bashekim bashekim = new Bashekim();
   
    private String ad;
    private String soyad;//nesne yönelimli programlama kurallarına uymak için değişkenler private tanımlanır
    private String parola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;
    private String unvan;

    /**
     * Creates new form BashekimBilgileriGoster
     */
    public BashekimBilgileriGoster() {
        initComponents();
        ad = BashekimEkrani.bashekimAdiniDondur();//BashekimEkrani ndan giriş yapan kullanıcının bilgileri
        //orada bulunan statik methotlar ile döndürülmüştür.
        //O bilgileri burada kullanabilmek için class adı ile methotlar burada çağırılarak tanımladığımız değişkenlere eşitlenir
        soyad = BashekimEkrani.bashekimSoyadiniDondur();
        
        tcNo = BashekimEkrani.bashekimTcNoDegeriDondur();
        mail = BashekimEkrani.bashekimMailDondur();
        cepTel = BashekimEkrani.bashekimCepTelDegeriDondur();
        adres = BashekimEkrani.bashekimAdresDondur();
        cinsiyet = BashekimEkrani.bashekimCinsiyetDondur();
        unvan = BashekimEkrani.bashekimUnvanDondur();
        id = BashekimEkrani.bashekimIdDegeriDondur();
        parola = bashekim.parolaGetir(id);//parolanın görünür olması için parolaGetir methotu ile id 'ye göre
        //kullanıcının parolası veritabanından getirilir . Ve parola değişkenine eşitlenir
        
        
       
        goster();//goster methodu ile bu alınan bilgiler kullanıcı bu ekranı açınca
        //setText ile uygun etiketlerde gösterilir
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cikisYap_butonu = new javax.swing.JButton();
        parolaGoster_alani = new javax.swing.JLabel();
        adGoster_alani = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        soyadGoster_alani = new javax.swing.JLabel();
        kimlikNoGoster_alani = new javax.swing.JLabel();
        unvanGoster_alani = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mailGoster_alani = new javax.swing.JLabel();
        telGoster_alani = new javax.swing.JLabel();
        adresGoster_alani = new javax.swing.JLabel();
        cinsiyetGoster_alani = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BAŞHEKİM BİLGİLERİ GÖSTER");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 204, 0)), "Bilgilerimi Göster", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel1.setLayout(null);

        cikisYap_butonu.setBackground(new java.awt.Color(255, 255, 0));
        cikisYap_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cikisYap_butonu.setForeground(new java.awt.Color(255, 51, 153));
        cikisYap_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\4700771_exit-power-off-icon-white-hd-png-download_50x50.jpg")); // NOI18N
        cikisYap_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        cikisYap_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYap_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(cikisYap_butonu);
        cikisYap_butonu.setBounds(1260, 50, 70, 60);

        parolaGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parolaGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        parolaGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(parolaGoster_alani);
        parolaGoster_alani.setBounds(420, 480, 190, 50);

        adGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        adGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(adGoster_alani);
        adGoster_alani.setBounds(420, 240, 190, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\kisspng-computer-icons-printing-management-creative-busine-high-end-business-card-design-5adcaba622c989.0449529915244113021425_100x100.jpg")); // NOI18N
        jLabel10.setText("                                 BİLGİLERİM");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 50, 580, 120);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 204), 4));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("        Tc Kimlik No");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 190, 170, 45);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("             Parola");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 270, 170, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("              Soyad");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 120, 170, 46);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("                 Ad");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 30, 180, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("            Ünvan");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 370, 170, 45);

        soyadGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soyadGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        soyadGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(soyadGoster_alani);
        soyadGoster_alani.setBounds(330, 120, 190, 50);

        kimlikNoGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kimlikNoGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        kimlikNoGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(kimlikNoGoster_alani);
        kimlikNoGoster_alani.setBounds(330, 190, 190, 50);

        unvanGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unvanGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        unvanGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(unvanGoster_alani);
        unvanGoster_alani.setBounds(330, 370, 190, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Cinsiyet");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(640, 370, 170, 45);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("              Adres");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(640, 230, 170, 100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Cep Telefon Numarası");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(640, 150, 170, 45);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("     Mail Adresi");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(640, 60, 170, 45);

        mailGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mailGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        mailGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(mailGoster_alani);
        mailGoster_alani.setBounds(890, 60, 190, 50);

        telGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        telGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(telGoster_alani);
        telGoster_alani.setBounds(890, 150, 190, 50);

        adresGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adresGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        adresGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(adresGoster_alani);
        adresGoster_alani.setBounds(890, 230, 190, 110);

        cinsiyetGoster_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinsiyetGoster_alani.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetGoster_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel2.add(cinsiyetGoster_alani);
        cinsiyetGoster_alani.setBounds(890, 370, 190, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 210, 1190, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void goster(){
        parolaGoster_alani.setText(ad);
        soyadGoster_alani.setText(soyad);
        parolaGoster_alani.setText(parola);
        kimlikNoGoster_alani.setText(tcNo);
        mailGoster_alani.setText(mail);
        telGoster_alani.setText(cepTel);
        adresGoster_alani.setText(adres);
        cinsiyetGoster_alani.setText(cinsiyet);
        unvanGoster_alani.setText(unvan);
    }
    private void cikisYap_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYap_butonuActionPerformed
        // TODO add your handling code here:
        dispose();//bulunduğumuz ekranı kapatır
    }//GEN-LAST:event_cikisYap_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BashekimBilgileriGoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adGoster_alani;
    private javax.swing.JLabel adresGoster_alani;
    private javax.swing.JButton cikisYap_butonu;
    private javax.swing.JLabel cinsiyetGoster_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kimlikNoGoster_alani;
    private javax.swing.JLabel mailGoster_alani;
    private javax.swing.JLabel parolaGoster_alani;
    private javax.swing.JLabel soyadGoster_alani;
    private javax.swing.JLabel telGoster_alani;
    private javax.swing.JLabel unvanGoster_alani;
    // End of variables declaration//GEN-END:variables
}
