/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Bashekim;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class BashekimBilgileriGuncelle extends javax.swing.JFrame {
    Bashekim bashekim = new Bashekim();
    private String isim;
    private String soyad;
    private String parola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;
    private String unvan;

    /**
     * Creates new form BashekimBilgileriGuncelle
     */
    public BashekimBilgileriGuncelle() {
        initComponents();
        isim = BashekimEkrani.bashekimAdiniDondur();
        soyad = BashekimEkrani.bashekimSoyadiniDondur();
        
        tcNo = BashekimEkrani.bashekimTcNoDegeriDondur();
        mail = BashekimEkrani.bashekimMailDondur();
        cepTel = BashekimEkrani.bashekimCepTelDegeriDondur();
        adres = BashekimEkrani.bashekimAdresDondur();
        id = BashekimEkrani.bashekimIdDegeriDondur();
        parola = bashekim.parolaGetir(id);
        bashekimAd_guncelle.setText(isim);
        bashekimSoyad_guncelle.setText(soyad);
        bashekimParola_guncelle.setText(parola);
        bashekimTc_guncelle.setText(tcNo);
        bashekimMail_guncelle.setText(mail);
        bashekimTel_guncelle.setText(cepTel);
        bashekimAdres_guncelle.setText(adres);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bashekimParola_guncelle = new javax.swing.JTextField();
        bashekimAd_guncelle = new javax.swing.JTextField();
        bashekimSoyad_guncelle = new javax.swing.JTextField();
        bashekimTc_guncelle = new javax.swing.JTextField();
        mesaj_etiketi = new javax.swing.JLabel();
        mesaj_etiketi2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bashekimMail_guncelle = new javax.swing.JTextField();
        bashekimTel_guncelle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bashekimAdres_guncelle = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bilgiGuncelle_butonu = new javax.swing.JButton();
        iptal_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BAŞHEKİM BİLGİLERİ GÜNCELLE");

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4), "Bilgilerimi Güncelle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 102))); // NOI18N
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("                 Adres");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(690, 410, 180, 110);

        bashekimParola_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimParola_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimParola_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimParola_guncelle);
        bashekimParola_guncelle.setBounds(400, 460, 186, 49);

        bashekimAd_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimAd_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimAd_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimAd_guncelle);
        bashekimAd_guncelle.setBounds(400, 160, 186, 49);

        bashekimSoyad_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimSoyad_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimSoyad_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimSoyad_guncelle);
        bashekimSoyad_guncelle.setBounds(400, 240, 186, 49);

        bashekimTc_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimTc_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimTc_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimTc_guncelle);
        bashekimTc_guncelle.setBounds(400, 340, 186, 49);
        jPanel1.add(mesaj_etiketi);
        mesaj_etiketi.setBounds(180, 290, 220, 30);
        jPanel1.add(mesaj_etiketi2);
        mesaj_etiketi2.setBounds(180, 410, 200, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("          Mail Adresi");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(690, 170, 180, 49);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Cep Telefon Numarası");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(690, 300, 180, 49);

        bashekimMail_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimMail_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimMail_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimMail_guncelle);
        bashekimMail_guncelle.setBounds(960, 170, 186, 49);

        bashekimTel_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimTel_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimTel_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(bashekimTel_guncelle);
        bashekimTel_guncelle.setBounds(970, 300, 186, 49);

        bashekimAdres_guncelle.setColumns(20);
        bashekimAdres_guncelle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bashekimAdres_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        bashekimAdres_guncelle.setRows(5);
        bashekimAdres_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jScrollPane1.setViewportView(bashekimAdres_guncelle);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(970, 410, 180, 110);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 4));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("                      Ad");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 80, 205, 49);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("                     Soyad");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 160, 205, 49);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("               Tc Kimlik No");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 260, 205, 49);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("                 Parola");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 380, 205, 49);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 80, 1180, 490);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel3.setLayout(null);

        bilgiGuncelle_butonu.setBackground(new java.awt.Color(102, 255, 204));
        bilgiGuncelle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilgiGuncelle_butonu.setForeground(new java.awt.Color(255, 0, 102));
        bilgiGuncelle_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\191-1918674_colour-change-icon-hd-png-download_50x50.jpg")); // NOI18N
        bilgiGuncelle_butonu.setText("Güncelle");
        bilgiGuncelle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        bilgiGuncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiGuncelle_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(bilgiGuncelle_butonu);
        bilgiGuncelle_butonu.setBounds(180, 10, 160, 60);

        iptal_butonu.setBackground(new java.awt.Color(102, 255, 204));
        iptal_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iptal_butonu.setForeground(new java.awt.Color(255, 0, 102));
        iptal_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        iptal_butonu.setText("İptal Et");
        iptal_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        iptal_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptal_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(iptal_butonu);
        iptal_butonu.setBounds(480, 10, 160, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 590, 730, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgiGuncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiGuncelle_butonuActionPerformed
        // TODO add your handling code here:
       String yeniAd =  bashekimAd_guncelle.getText();
       String yeniSoyad = bashekimSoyad_guncelle.getText();
       String yeniParola = bashekimParola_guncelle.getText();
       String yeniTcNo = bashekimTc_guncelle.getText();
       String yeniMail = bashekimMail_guncelle.getText();
       String yeniCepTel = bashekimTel_guncelle.getText();
       String yeniAdres = bashekimAdres_guncelle.getText();
       if(bashekimAd_guncelle.getText().length()==0 || bashekimSoyad_guncelle.getText().length()==0 || bashekimParola_guncelle.getText().length()==0 || bashekimTc_guncelle.getText().length()==0 || bashekimMail_guncelle.getText().length()==0 || bashekimTel_guncelle.getText().length()==0 || bashekimAdres_guncelle.getText().length()==0){
           YardimciMethotlar.mesajGoster("dolu");
       }
       else{
           
           if(yeniParola.length()<8 || yeniTcNo.length()!=11){//Parola ve tc için boyut kontrolü yapar
               if(yeniParola.length()<8){
                    mesaj_etiketi2.setText("Parolanız en az 8 haneli olmalıdır !!!");
           
       }
               if(yeniTcNo.length()!=11){
                    mesaj_etiketi.setText("Tc kimlik numarası 11 hane dışında olamaz!!!");
               
           }
           
       }
            else{
                 boolean kontrol = bashekim.bilgilerimiGuncelle(id, yeniAd,yeniSoyad, yeniTcNo, yeniParola,yeniMail,yeniCepTel,yeniAdres);//Bashekim class'ı içindeki bilgilerimiGuncelle methodu ile başhemin bilgilerini günceller
                 if(kontrol){
                     YardimciMethotlar.mesajGoster("basarili");
           }
                 else{
                     YardimciMethotlar.mesajGoster("error");
           }
           
       }
           
       }
       
    }//GEN-LAST:event_bilgiGuncelle_butonuActionPerformed

    private void iptal_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptal_butonuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_iptal_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BashekimBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BashekimBilgileriGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bashekimAd_guncelle;
    private javax.swing.JTextArea bashekimAdres_guncelle;
    private javax.swing.JTextField bashekimMail_guncelle;
    private javax.swing.JTextField bashekimParola_guncelle;
    private javax.swing.JTextField bashekimSoyad_guncelle;
    private javax.swing.JTextField bashekimTc_guncelle;
    private javax.swing.JTextField bashekimTel_guncelle;
    private javax.swing.JButton bilgiGuncelle_butonu;
    private javax.swing.JButton iptal_butonu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_etiketi;
    private javax.swing.JLabel mesaj_etiketi2;
    // End of variables declaration//GEN-END:variables
}
