/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.YoneticiIslemleri;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class BashekimAtamaEkrani extends javax.swing.JFrame {
     private long parola = 10000000+(int)(Math.random()* 90000000);
     //Sisteme yeni kaydedilecek bir başhekim için rastgele 8 haneli şifre atamasının sistem tarafından otomatik yapılması sağlanır
     private String parola2 = String.valueOf(parola);
     YoneticiIslemleri yoneticiIslem = new YoneticiIslemleri();

    /**
     * Creates new form BashekimAtamaEkrani
     */
    public BashekimAtamaEkrani() {
        initComponents();
        bashekimParola_alani.setText(parola2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bashekimParola_alani = new javax.swing.JTextField();
        cinsiyetSec_box = new javax.swing.JComboBox<>();
        geri_butonu = new javax.swing.JButton();
        mesaj_etiketi = new javax.swing.JLabel();
        mesaj_etiketi1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bashekimTc_alani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bashekimAd_alani = new javax.swing.JTextField();
        bashekimSoyad_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unvanSec_alani = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bashekimAdres_alani = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bashekimCep_alani = new javax.swing.JTextField();
        bashekimMail_alani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bashekimAta_butonu = new javax.swing.JButton();
        atamaIptali_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BAŞHEKİM ATAMA EKRANI");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("       Tc Kimlik No");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 130, 159, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("        Parola");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 380, 150, 40);

        bashekimParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(bashekimParola_alani);
        bashekimParola_alani.setBounds(430, 380, 160, 40);

        cinsiyetSec_box.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinsiyetSec_box.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetSec_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Cinsiyet Seç--", "Kadın", "Erkek", "Diğer", " " }));
        cinsiyetSec_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(cinsiyetSec_box);
        cinsiyetSec_box.setBounds(430, 480, 160, 40);

        geri_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        geri_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\back-158491_1280_50x50.jpg")); // NOI18N
        geri_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        geri_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(geri_butonu);
        geri_butonu.setBounds(1290, 10, 59, 60);
        jPanel1.add(mesaj_etiketi);
        mesaj_etiketi.setBounds(130, 400, 300, 20);
        jPanel1.add(mesaj_etiketi1);
        mesaj_etiketi1.setBounds(130, 140, 280, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("                                          BAŞHEKİM ATAMA EKRANI");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 30, 660, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        jPanel2.setLayout(null);

        bashekimTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(bashekimTc_alani);
        bashekimTc_alani.setBounds(300, 40, 160, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("              Ad");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 120, 150, 40);

        bashekimAd_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimAd_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimAd_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(bashekimAd_alani);
        bashekimAd_alani.setBounds(300, 130, 160, 40);

        bashekimSoyad_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimSoyad_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimSoyad_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(bashekimSoyad_alani);
        bashekimSoyad_alani.setBounds(300, 210, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("          Soyad");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 210, 150, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("          Cinsiyet");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 390, 150, 40);

        unvanSec_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unvanSec_alani.setForeground(new java.awt.Color(255, 0, 0));
        unvanSec_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Başhekim Ünvanı Seç--", "Ordinaryus", "Prof", "Doç", "Yardımcı Doçent", "Operatör", "Uzman", "Pratisyen", " " }));
        unvanSec_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(unvanSec_alani);
        unvanSec_alani.setBounds(870, 390, 220, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("             Ünvan");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(610, 390, 170, 40);

        bashekimAdres_alani.setColumns(20);
        bashekimAdres_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimAdres_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimAdres_alani.setRows(5);
        bashekimAdres_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jScrollPane1.setViewportView(bashekimAdres_alani);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(870, 260, 220, 90);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("                Adres");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(610, 270, 170, 80);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Cep Telefon Numarası");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(610, 180, 170, 40);

        bashekimCep_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimCep_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimCep_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(bashekimCep_alani);
        bashekimCep_alani.setBounds(870, 170, 220, 50);

        bashekimMail_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimMail_alani.setForeground(new java.awt.Color(255, 0, 0));
        bashekimMail_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(bashekimMail_alani);
        bashekimMail_alani.setBounds(870, 80, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 102));
        jLabel6.setText("            Mail Adresi");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(610, 80, 170, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 90, 1150, 490);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 4));
        jPanel3.setLayout(null);

        bashekimAta_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimAta_butonu.setForeground(new java.awt.Color(255, 0, 0));
        bashekimAta_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\vector-add-icon_50x50.jpg")); // NOI18N
        bashekimAta_butonu.setText("Başhekim Ata");
        bashekimAta_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        bashekimAta_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashekimAta_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(bashekimAta_butonu);
        bashekimAta_butonu.setBounds(90, 30, 170, 40);

        atamaIptali_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atamaIptali_butonu.setForeground(new java.awt.Color(255, 0, 0));
        atamaIptali_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        atamaIptali_butonu.setText("İptal Et");
        atamaIptali_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        atamaIptali_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atamaIptali_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(atamaIptali_butonu);
        atamaIptali_butonu.setBounds(410, 30, 140, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 590, 630, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bashekimAta_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashekimAta_butonuActionPerformed
        // TODO add your handling code here:
        //Sisteme yeni başhemin atanmasını sağlar
         if(bashekimTc_alani.getText().length()==0 || bashekimParola_alani.getText().length()==0 || bashekimAd_alani.getText().length()==0 || bashekimSoyad_alani.getText().length()==0 || bashekimMail_alani.getText().length()==0 || bashekimCep_alani.getText().length()==0 || bashekimAdres_alani.getText().length()==0 || cinsiyetSec_box.getSelectedIndex()==0 || unvanSec_alani.getSelectedIndex()==0 ){
            YardimciMethotlar.mesajGoster("dolu");
        }
         else{
             
             String tc = bashekimTc_alani.getText();
             String sifre = bashekimParola_alani.getText();//Arayüzden yeni başhekim için girilen bilgileri alır
             String ad = bashekimAd_alani.getText();
             String soyad = bashekimSoyad_alani.getText();
             String mail = bashekimMail_alani.getText();
             String cepTel = bashekimCep_alani.getText();
             String adres = bashekimAdres_alani.getText();
             String cinsiyet = (String) cinsiyetSec_box.getSelectedItem();
             String unvan = (String) unvanSec_alani.getSelectedItem();
              if(bashekimParola_alani.getText().length()<8 || bashekimTc_alani.getText().length()!=11){
                if(sifre.length()<8){
                    mesaj_etiketi.setText("Parola en az 8 karakterden oluşmalıdır!!!!!");
                    
                }
                if(tc.length()!=11){
                    mesaj_etiketi1.setText("Tc kimlik numarası 11 haneli olmalıdır!!");
                    
                }
            }
              else{
                  
                     boolean durum = yoneticiIslem.bashekimEkle(tc, sifre, ad, soyad, mail, cepTel, adres, cinsiyet, unvan);
                     //YoneticiIslemleri classından oluşturduğum yoneticiIslem nesnesi aracılığıyla
                     //içindeki bashekimEkle methodunu kullanarak veritabanına ekleme işlemini gerçekleştirir.
                     if(durum){
                       YardimciMethotlar.mesajGoster("basarili");
        }
                     else{
                       YardimciMethotlar.mesajGoster("hata");
        }
                  
              }
             
          
             
         }
        
    }//GEN-LAST:event_bashekimAta_butonuActionPerformed

    private void atamaIptali_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atamaIptali_butonuActionPerformed
        // TODO add your handling code here:
        YardimciMethotlar.mesajGoster("eminim");
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
    }//GEN-LAST:event_atamaIptali_butonuActionPerformed

    private void geri_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_butonuActionPerformed
        // TODO add your handling code here:
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_geri_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BashekimAtamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BashekimAtamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BashekimAtamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BashekimAtamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BashekimAtamaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atamaIptali_butonu;
    private javax.swing.JTextField bashekimAd_alani;
    private javax.swing.JTextArea bashekimAdres_alani;
    private javax.swing.JButton bashekimAta_butonu;
    private javax.swing.JTextField bashekimCep_alani;
    private javax.swing.JTextField bashekimMail_alani;
    private javax.swing.JTextField bashekimParola_alani;
    private javax.swing.JTextField bashekimSoyad_alani;
    private javax.swing.JTextField bashekimTc_alani;
    private javax.swing.JComboBox<String> cinsiyetSec_box;
    private javax.swing.JButton geri_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_etiketi;
    private javax.swing.JLabel mesaj_etiketi1;
    private javax.swing.JComboBox<String> unvanSec_alani;
    // End of variables declaration//GEN-END:variables
}
