/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Doktor;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class DoktorBilgileriGuncelle extends javax.swing.JFrame {
    Doktor doktor = new Doktor();//Doktor classını tanımladık
    private String ad;
    private String soyad;
    private String parola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;
    private String unvan;

    /**
     * Creates new form DoktorBilgileriGuncelle
     */
    public DoktorBilgileriGuncelle() {
        initComponents();
        ad = DoktorEkrani.doktorAdiniDondur();//sisteme giriş yapan doktorun bilgilerini alırız
        soyad = DoktorEkrani.doktorSoyadiniDondur();
        
        tcNo = DoktorEkrani.doktorTcNoDegeriDondur();
        
        mail = DoktorEkrani.doktorMailDondur();
        cepTel = DoktorEkrani.doktorCepTelDegeriDondur();
        
        adres = DoktorEkrani.doktorAdresDondur();
        cinsiyet = DoktorEkrani.doktorCinsiyetDondur();
        unvan = DoktorEkrani.doktorUnvanDondur();
        id = DoktorEkrani.doktorIdDegeriDondur();
        parola = doktor.parolaGetir(id);
        doktorAd_guncelle.setText(ad);
        doktorSoyad_guncelle.setText(soyad);
        doktorParola_guncelle.setText(parola);
        doktorTc_guncelle.setText(tcNo);
        doktorMail_guncelle.setText(mail);
        doktorTel_guncelle.setText(cepTel);
        doktorAdres_guncelle.setText(adres);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelll1 = new javax.swing.JPanel();
        mesaj_etiketi = new javax.swing.JLabel();
        mesaj_etiketi2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelll8 = new javax.swing.JLabel();
        jLabelll4 = new javax.swing.JLabel();
        jLabelll5 = new javax.swing.JLabel();
        jLabelll6 = new javax.swing.JLabel();
        doktorAd_guncelle = new javax.swing.JTextField();
        doktorSoyad_guncelle = new javax.swing.JTextField();
        doktorTc_guncelle = new javax.swing.JTextField();
        doktorParola_guncelle = new javax.swing.JTextField();
        jLabelll9 = new javax.swing.JLabel();
        jLabelll10 = new javax.swing.JLabel();
        jLabelll11 = new javax.swing.JLabel();
        jLabelll7 = new javax.swing.JLabel();
        doktorMail_guncelle = new javax.swing.JTextField();
        doktorTel_guncelle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doktorAdres_guncelle = new javax.swing.JTextArea();
        doktorUnvaniGuncelle_box = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        bilgiGuncelle_butonu2 = new javax.swing.JButton();
        iptal_butonu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DOKTOR BİLGİLERİ GÜNCELLE");

        jPanelll1.setBackground(new java.awt.Color(102, 255, 204));
        jPanelll1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4), "Bilgilerimi Güncelle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 102))); // NOI18N
        jPanelll1.setLayout(null);
        jPanelll1.add(mesaj_etiketi);
        mesaj_etiketi.setBounds(180, 290, 220, 30);
        jPanelll1.add(mesaj_etiketi2);
        mesaj_etiketi2.setBounds(180, 410, 200, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.setLayout(null);

        jLabelll8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll8.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll8.setText("                      Ad");
        jLabelll8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll8);
        jLabelll8.setBounds(80, 50, 205, 49);

        jLabelll4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll4.setText("                     Soyad");
        jLabelll4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll4);
        jLabelll4.setBounds(80, 170, 205, 49);

        jLabelll5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll5.setText("               Tc Kimlik No");
        jLabelll5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll5);
        jLabelll5.setBounds(80, 290, 205, 49);

        jLabelll6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll6.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll6.setText("                 Parola");
        jLabelll6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll6);
        jLabelll6.setBounds(80, 410, 205, 49);

        doktorAd_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorAd_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorAd_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorAd_guncelle);
        doktorAd_guncelle.setBounds(340, 50, 186, 49);

        doktorSoyad_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorSoyad_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorSoyad_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorSoyad_guncelle);
        doktorSoyad_guncelle.setBounds(340, 160, 186, 49);

        doktorTc_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorTc_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorTc_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorTc_guncelle);
        doktorTc_guncelle.setBounds(340, 290, 186, 49);

        doktorParola_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorParola_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorParola_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorParola_guncelle);
        doktorParola_guncelle.setBounds(340, 410, 186, 49);

        jLabelll9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll9.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll9.setText("         Mail Adresi");
        jLabelll9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll9);
        jLabelll9.setBounds(610, 40, 180, 49);

        jLabelll10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll10.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll10.setText("Cep Telefon Numarası");
        jLabelll10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll10);
        jLabelll10.setBounds(610, 150, 180, 49);

        jLabelll11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll11.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll11.setText("               Adres");
        jLabelll11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll11);
        jLabelll11.setBounds(610, 250, 180, 100);

        jLabelll7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelll7.setForeground(new java.awt.Color(255, 0, 0));
        jLabelll7.setText("               Unvan");
        jLabelll7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabelll7);
        jLabelll7.setBounds(610, 400, 180, 49);

        doktorMail_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorMail_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorMail_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorMail_guncelle);
        doktorMail_guncelle.setBounds(850, 40, 186, 49);

        doktorTel_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorTel_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorTel_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorTel_guncelle);
        doktorTel_guncelle.setBounds(850, 150, 186, 49);

        doktorAdres_guncelle.setColumns(20);
        doktorAdres_guncelle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        doktorAdres_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        doktorAdres_guncelle.setRows(5);
        doktorAdres_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jScrollPane1.setViewportView(doktorAdres_guncelle);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(860, 250, 180, 110);

        doktorUnvaniGuncelle_box.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doktorUnvaniGuncelle_box.setForeground(new java.awt.Color(255, 0, 0));
        doktorUnvaniGuncelle_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Doktor Ünvanı Seç--", "Ordinaryus", "Prof", "Doç", "Yardımcı Doçent", "Operatör", "Uzman", "Pratisyen" }));
        doktorUnvaniGuncelle_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(doktorUnvaniGuncelle_box);
        doktorUnvaniGuncelle_box.setBounds(860, 390, 180, 50);

        jPanelll1.add(jPanel1);
        jPanel1.setBounds(70, 70, 1180, 500);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel2.setLayout(null);

        bilgiGuncelle_butonu2.setBackground(new java.awt.Color(102, 255, 204));
        bilgiGuncelle_butonu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilgiGuncelle_butonu2.setForeground(new java.awt.Color(255, 0, 102));
        bilgiGuncelle_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\191-1918674_colour-change-icon-hd-png-download_50x50.jpg")); // NOI18N
        bilgiGuncelle_butonu2.setText("Güncelle");
        bilgiGuncelle_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        bilgiGuncelle_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiGuncelle_butonu2ActionPerformed(evt);
            }
        });
        jPanel2.add(bilgiGuncelle_butonu2);
        bilgiGuncelle_butonu2.setBounds(240, 30, 170, 50);

        iptal_butonu2.setBackground(new java.awt.Color(102, 255, 204));
        iptal_butonu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iptal_butonu2.setForeground(new java.awt.Color(255, 0, 102));
        iptal_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        iptal_butonu2.setText("İptal Et");
        iptal_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        iptal_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptal_butonu2ActionPerformed(evt);
            }
        });
        jPanel2.add(iptal_butonu2);
        iptal_butonu2.setBounds(550, 30, 160, 50);

        jPanelll1.add(jPanel2);
        jPanel2.setBounds(240, 580, 880, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelll1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelll1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgiGuncelle_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiGuncelle_butonu2ActionPerformed
        // TODO add your handling code here:
        String yeniAd =  doktorAd_guncelle.getText();
        String yeniSoyad = doktorSoyad_guncelle.getText();
        String yeniParola = doktorParola_guncelle.getText();
        String yeniTcNo = doktorTc_guncelle.getText();
        String yeniMail = doktorMail_guncelle.getText();
        String yeniCepTel = doktorTel_guncelle.getText();
        String yeniAdres = doktorAdres_guncelle.getText();
        String yeniUnvan = (String) doktorUnvaniGuncelle_box.getSelectedItem();
        if(doktorAd_guncelle.getText().length()==0 || doktorSoyad_guncelle.getText().length()==0 || doktorParola_guncelle.getText().length()==0 || doktorTc_guncelle.getText().length()==0 || doktorMail_guncelle.getText().length()==0 || doktorTel_guncelle.getText().length()==0 || doktorAdres_guncelle.getText().length()==0 || doktorUnvaniGuncelle_box.getSelectedIndex()==0){
            YardimciMethotlar.mesajGoster("dolu");
        }
        else{

            if(yeniParola.length()<8 || yeniTcNo.length()!=11){
                if(yeniParola.length()<8){
                    mesaj_etiketi2.setText("Parolanız en az 8 haneli olmalıdır !!!");

                }
                if(yeniTcNo.length()!=11){
                    mesaj_etiketi.setText("Tc kimlik numarası 11 hane dışında olamaz!!!");

                }

            }
            else{
                boolean kontrol = doktor.doktorBilgileriniGuncelle(id, yeniAd,yeniSoyad, yeniTcNo, yeniParola,yeniMail,yeniCepTel,yeniAdres,yeniUnvan);//giriş yapan doktorun id'sine göre doktor bilgi güncellemesi yapar
                if(kontrol){
                    YardimciMethotlar.mesajGoster("basarili");
                }
                else{
                    YardimciMethotlar.mesajGoster("hata");
                }

            }

        }

    }//GEN-LAST:event_bilgiGuncelle_butonu2ActionPerformed

    private void iptal_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptal_butonu2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_iptal_butonu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorBilgileriGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgiGuncelle_butonu2;
    private javax.swing.JTextField doktorAd_guncelle;
    private javax.swing.JTextArea doktorAdres_guncelle;
    private javax.swing.JTextField doktorMail_guncelle;
    private javax.swing.JTextField doktorParola_guncelle;
    private javax.swing.JTextField doktorSoyad_guncelle;
    private javax.swing.JTextField doktorTc_guncelle;
    private javax.swing.JTextField doktorTel_guncelle;
    private javax.swing.JComboBox<String> doktorUnvaniGuncelle_box;
    private javax.swing.JButton iptal_butonu2;
    private javax.swing.JLabel jLabelll10;
    private javax.swing.JLabel jLabelll11;
    private javax.swing.JLabel jLabelll4;
    private javax.swing.JLabel jLabelll5;
    private javax.swing.JLabel jLabelll6;
    private javax.swing.JLabel jLabelll7;
    private javax.swing.JLabel jLabelll8;
    private javax.swing.JLabel jLabelll9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelll1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_etiketi;
    private javax.swing.JLabel mesaj_etiketi2;
    // End of variables declaration//GEN-END:variables
}
