/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Doktor;

/**
 *
 * @author İREM SAMUR
 */
public class DoktorBilgileriGoster extends javax.swing.JFrame {
    Doktor doktor = new Doktor();
    private String ad;
    private String soyad;
    private String parola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;
    private String unvan;

    /**
     * Creates new form DoktorBilgileriGoster
     */
    public DoktorBilgileriGoster() {
        initComponents();
        ad = DoktorEkrani.doktorAdiniDondur();
        soyad = DoktorEkrani.doktorSoyadiniDondur();
        
        tcNo = DoktorEkrani.doktorTcNoDegeriDondur();
        
        mail = DoktorEkrani.doktorMailDondur();
        cepTel = DoktorEkrani.doktorCepTelDegeriDondur();
        //System.out.println(cepTel);
        adres = DoktorEkrani.doktorAdresDondur();
        cinsiyet = DoktorEkrani.doktorCinsiyetDondur();
        unvan = DoktorEkrani.doktorUnvanDondur();
        id = DoktorEkrani.doktorIdDegeriDondur();
        parola = doktor.parolaGetir(id);
        
        bilgileriGoster();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanell1 = new javax.swing.JPanel();
        cikisYap_butonu2 = new javax.swing.JButton();
        cinsiyetGoster_alani2 = new javax.swing.JLabel();
        mailGoster_alani2 = new javax.swing.JLabel();
        adresGoster_alani2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        adGoster_alani2 = new javax.swing.JLabel();
        jLabell5 = new javax.swing.JLabel();
        jLabell2 = new javax.swing.JLabel();
        soyadGoster_alani2 = new javax.swing.JLabel();
        kimlikNoGoster_alani2 = new javax.swing.JLabel();
        jLabell3 = new javax.swing.JLabel();
        jLabell4 = new javax.swing.JLabel();
        parolaGoster_alani2 = new javax.swing.JLabel();
        jLabell6 = new javax.swing.JLabel();
        telGoster_alani2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabell8 = new javax.swing.JLabel();
        jLabell9 = new javax.swing.JLabel();
        jLabell1 = new javax.swing.JLabel();
        unvanGoster_alani2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DOKTOR BİLGİLERİ GÖSTER");

        jPanell1.setBackground(new java.awt.Color(153, 255, 204));
        jPanell1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 204, 0)), "Bilgilerimi Göster", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanell1.setLayout(null);

        cikisYap_butonu2.setBackground(new java.awt.Color(255, 255, 0));
        cikisYap_butonu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cikisYap_butonu2.setForeground(new java.awt.Color(255, 51, 153));
        cikisYap_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\342-0-0-0-10000-10000-1690_50x50.jpg")); // NOI18N
        cikisYap_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        cikisYap_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYap_butonu2ActionPerformed(evt);
            }
        });
        jPanell1.add(cikisYap_butonu2);
        cikisYap_butonu2.setBounds(1270, 30, 60, 40);

        cinsiyetGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinsiyetGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell1.add(cinsiyetGoster_alani2);
        cinsiyetGoster_alani2.setBounds(950, 510, 190, 50);

        mailGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mailGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        mailGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell1.add(mailGoster_alani2);
        mailGoster_alani2.setBounds(950, 240, 190, 50);

        adresGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adresGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        adresGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell1.add(adresGoster_alani2);
        adresGoster_alani2.setBounds(950, 390, 190, 90);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\kisspng-computer-icons-printing-management-creative-busine-high-end-business-card-design-5adcaba622c989.0449529915244113021425_100x100.jpg")); // NOI18N
        jLabel12.setText("                BİLGİLERİM");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell1.add(jLabel12);
        jLabel12.setBounds(450, 30, 390, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255), 4));
        jPanel1.setLayout(null);

        adGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        adGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(adGoster_alani2);
        adGoster_alani2.setBounds(260, 80, 190, 50);

        jLabell5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell5.setForeground(new java.awt.Color(255, 0, 0));
        jLabell5.setText("           Ad");
        jLabell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell5);
        jLabell5.setBounds(50, 80, 132, 45);

        jLabell2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell2.setForeground(new java.awt.Color(255, 0, 0));
        jLabell2.setText("        Soyad");
        jLabell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell2);
        jLabell2.setBounds(50, 180, 132, 46);

        soyadGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soyadGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        soyadGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(soyadGoster_alani2);
        soyadGoster_alani2.setBounds(260, 180, 190, 50);

        kimlikNoGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kimlikNoGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        kimlikNoGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(kimlikNoGoster_alani2);
        kimlikNoGoster_alani2.setBounds(260, 290, 190, 50);

        jLabell3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell3.setForeground(new java.awt.Color(255, 0, 0));
        jLabell3.setText("   Tc Kimlik No");
        jLabell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell3);
        jLabell3.setBounds(50, 290, 132, 45);

        jLabell4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell4.setForeground(new java.awt.Color(255, 0, 0));
        jLabell4.setText("        Parola");
        jLabell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell4);
        jLabell4.setBounds(50, 390, 132, 48);

        parolaGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parolaGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        parolaGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(parolaGoster_alani2);
        parolaGoster_alani2.setBounds(260, 380, 190, 50);

        jLabell6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell6.setForeground(new java.awt.Color(255, 0, 0));
        jLabell6.setText("     Mail Adresi");
        jLabell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell6);
        jLabell6.setBounds(550, 60, 170, 45);

        telGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        telGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(telGoster_alani2);
        telGoster_alani2.setBounds(860, 130, 190, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Cep Telefon Numarası");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 140, 170, 45);

        jLabell8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell8.setForeground(new java.awt.Color(255, 0, 0));
        jLabell8.setText("                Adres");
        jLabell8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell8);
        jLabell8.setBounds(550, 210, 170, 90);

        jLabell9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell9.setForeground(new java.awt.Color(255, 0, 0));
        jLabell9.setText("             Cinsiyet");
        jLabell9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell9);
        jLabell9.setBounds(550, 330, 170, 45);

        jLabell1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabell1.setForeground(new java.awt.Color(255, 0, 0));
        jLabell1.setText("             Ünvan");
        jLabell1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabell1);
        jLabell1.setBounds(550, 400, 170, 45);

        unvanGoster_alani2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unvanGoster_alani2.setForeground(new java.awt.Color(255, 0, 0));
        unvanGoster_alani2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(unvanGoster_alani2);
        unvanGoster_alani2.setBounds(860, 400, 190, 50);

        jPanell1.add(jPanel1);
        jPanel1.setBounds(90, 180, 1150, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanell1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanell1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void bilgileriGoster(){
        //System.out.println(cepTel);
        adGoster_alani2.setText(ad);
        soyadGoster_alani2.setText(soyad);
        parolaGoster_alani2.setText(parola);
        kimlikNoGoster_alani2.setText(tcNo);
        mailGoster_alani2.setText(mail);
        telGoster_alani2.setText(cepTel);
        adresGoster_alani2.setText(adres);
        cinsiyetGoster_alani2.setText(cinsiyet);
        unvanGoster_alani2.setText(unvan);
    }
    private void cikisYap_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYap_butonu2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cikisYap_butonu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorBilgileriGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorBilgileriGoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adGoster_alani2;
    private javax.swing.JLabel adresGoster_alani2;
    private javax.swing.JButton cikisYap_butonu2;
    private javax.swing.JLabel cinsiyetGoster_alani2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JLabel jLabell2;
    private javax.swing.JLabel jLabell3;
    private javax.swing.JLabel jLabell4;
    private javax.swing.JLabel jLabell5;
    private javax.swing.JLabel jLabell6;
    private javax.swing.JLabel jLabell8;
    private javax.swing.JLabel jLabell9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanell1;
    private javax.swing.JLabel kimlikNoGoster_alani2;
    private javax.swing.JLabel mailGoster_alani2;
    private javax.swing.JLabel parolaGoster_alani2;
    private javax.swing.JLabel soyadGoster_alani2;
    private javax.swing.JLabel telGoster_alani2;
    private javax.swing.JLabel unvanGoster_alani2;
    // End of variables declaration//GEN-END:variables
}
