/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.ResepsiyonistIslemleri;
import com.irem.veritabani.YardimciMethotlar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author İREM SAMUR
 */
public class HastaKayitIslemleri extends javax.swing.JFrame {
     ResepsiyonistIslemleri resepsiyonist = new ResepsiyonistIslemleri();
     Date simdikiZaman = new Date();
        
     DateFormat df = new SimpleDateFormat("yyyy");
        
     private String tarih = df.format(simdikiZaman);
     private int simdikiYil = Integer.valueOf(tarih);//şimdiki tarihi alır yılı int'e çevirir

    /**
     * Creates new form HastaKayitİslemleri
     */
    public HastaKayitIslemleri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanell1 = new javax.swing.JPanel();
        jPanell2 = new javax.swing.JPanel();
        kayit_resim2 = new javax.swing.JLabel();
        jLabell5 = new javax.swing.JLabel();
        jLabell6 = new javax.swing.JLabel();
        jPanell5 = new javax.swing.JPanel();
        kaydet_butonu = new javax.swing.JButton();
        temizle_butonu = new javax.swing.JButton();
        geri_butonu = new javax.swing.JButton();
        jPanell3 = new javax.swing.JPanel();
        jLabell7 = new javax.swing.JLabel();
        ad_labell = new javax.swing.JLabel();
        soyad_labell = new javax.swing.JLabel();
        kimlik_labell = new javax.swing.JLabel();
        hastaKayitAd_alani = new javax.swing.JTextField();
        hastaKayitSoyad_alani = new javax.swing.JTextField();
        hastaKayitTc_alani = new javax.swing.JTextField();
        cinsiyet_labell = new javax.swing.JLabel();
        hastaCinsiyetSec_alani = new javax.swing.JComboBox<>();
        mesaj_etiketi1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hastaKayitDogum_sec = new com.toedter.calendar.JDateChooser();
        jPanell4 = new javax.swing.JPanel();
        jLabell9 = new javax.swing.JLabel();
        mail_labell = new javax.swing.JLabel();
        jLabell10 = new javax.swing.JLabel();
        parola_labell = new javax.swing.JLabel();
        jLabell11 = new javax.swing.JLabel();
        hastaKayitMail_alani = new javax.swing.JTextField();
        hastaKayitCepTel_alani = new javax.swing.JTextField();
        hastaKayitParola_alani = new javax.swing.JPasswordField();
        jLabell12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hastaKayitAdres_alani = new javax.swing.JTextArea();
        mesaj_etiketi2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTA KAYIT İŞLEMLERİ");

        jPanell1.setBackground(new java.awt.Color(0, 255, 204));
        jPanell1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 0, 102)), "Hasta Kayıt Ekranı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanell1.setLayout(null);

        jPanell2.setBackground(new java.awt.Color(255, 51, 204));
        jPanell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 4));
        jPanell2.setLayout(null);

        kayit_resim2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\register_200x200.jpg")); // NOI18N
        kayit_resim2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));
        jPanell2.add(kayit_resim2);
        kayit_resim2.setBounds(390, 10, 208, 191);

        jLabell5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabell5.setForeground(new java.awt.Color(0, 102, 204));
        jLabell5.setText("                          HASTA KAYIT EKRANI");
        jLabell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanell2.add(jLabell5);
        jLabell5.setBounds(630, 70, 500, 65);

        jLabell6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabell6.setForeground(new java.awt.Color(0, 0, 204));
        jLabell6.setText("Hesap oluşturup, kaydınızı tamamlamak için lütfen aşağıdaki bilgilerin tamamını doldurunuz. (Tüm bilgilerin doldurulması zorunludur.)");
        jLabell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanell2.add(jLabell6);
        jLabell6.setBounds(110, 210, 842, 22);

        jPanell1.add(jPanell2);
        jPanell2.setBounds(20, 30, 1290, 254);

        jPanell5.setBackground(new java.awt.Color(0, 204, 153));
        jPanell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));

        kaydet_butonu.setBackground(new java.awt.Color(153, 255, 204));
        kaydet_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kaydet_butonu.setForeground(new java.awt.Color(255, 0, 204));
        kaydet_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\112-1123853_group-demos-access-user-icon_50x50.jpg")); // NOI18N
        kaydet_butonu.setText("Kaydet");
        kaydet_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        kaydet_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydet_butonuActionPerformed(evt);
            }
        });

        temizle_butonu.setBackground(new java.awt.Color(153, 255, 204));
        temizle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        temizle_butonu.setForeground(new java.awt.Color(255, 0, 204));
        temizle_butonu.setText("Bilgileri Temizle");
        temizle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        temizle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizle_butonuActionPerformed(evt);
            }
        });

        geri_butonu.setBackground(new java.awt.Color(153, 255, 204));
        geri_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        geri_butonu.setForeground(new java.awt.Color(255, 0, 204));
        geri_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\89-891085_reverse-icon-red-back-icon-png_50x50.jpg")); // NOI18N
        geri_butonu.setText("Geri");
        geri_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        geri_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanell5Layout = new javax.swing.GroupLayout(jPanell5);
        jPanell5.setLayout(jPanell5Layout);
        jPanell5Layout.setHorizontalGroup(
            jPanell5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanell5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kaydet_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temizle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(geri_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanell5Layout.setVerticalGroup(
            jPanell5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanell5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanell5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temizle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geri_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanell1.add(jPanell5);
        jPanell5.setBounds(20, 590, 680, 100);

        jPanell3.setBackground(new java.awt.Color(255, 255, 0));
        jPanell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell3.setLayout(null);

        jLabell7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell7.setForeground(new java.awt.Color(255, 0, 0));
        jLabell7.setText("                       Kişisel Bilgiler");
        jLabell7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanell3.add(jLabell7);
        jLabell7.setBounds(226, 24, 281, 35);

        ad_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ad_labell.setForeground(new java.awt.Color(255, 0, 102));
        ad_labell.setText("      Ad");
        ad_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell3.add(ad_labell);
        ad_labell.setBounds(30, 100, 110, 40);

        soyad_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        soyad_labell.setForeground(new java.awt.Color(255, 0, 102));
        soyad_labell.setText("   Soyad");
        soyad_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell3.add(soyad_labell);
        soyad_labell.setBounds(30, 190, 89, 38);

        kimlik_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kimlik_labell.setForeground(new java.awt.Color(255, 0, 102));
        kimlik_labell.setText("Tc Kimlik No");
        kimlik_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell3.add(kimlik_labell);
        kimlik_labell.setBounds(370, 100, 89, 38);

        hastaKayitAd_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaKayitAd_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitAd_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanell3.add(hastaKayitAd_alani);
        hastaKayitAd_alani.setBounds(180, 100, 128, 40);

        hastaKayitSoyad_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaKayitSoyad_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitSoyad_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanell3.add(hastaKayitSoyad_alani);
        hastaKayitSoyad_alani.setBounds(180, 190, 128, 38);

        hastaKayitTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaKayitTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanell3.add(hastaKayitTc_alani);
        hastaKayitTc_alani.setBounds(490, 100, 161, 38);

        cinsiyet_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cinsiyet_labell.setForeground(new java.awt.Color(255, 0, 102));
        cinsiyet_labell.setText("   Cinsiyet");
        cinsiyet_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell3.add(cinsiyet_labell);
        cinsiyet_labell.setBounds(370, 190, 84, 37);

        hastaCinsiyetSec_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaCinsiyetSec_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaCinsiyetSec_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kadın", "Erkek", "Diğer" }));
        hastaCinsiyetSec_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanell3.add(hastaCinsiyetSec_alani);
        hastaCinsiyetSec_alani.setBounds(490, 190, 161, 37);

        mesaj_etiketi1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mesaj_etiketi1.setForeground(new java.awt.Color(255, 0, 0));
        jPanell3.add(mesaj_etiketi1);
        mesaj_etiketi1.setBounds(360, 150, 290, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Hasta Doğum Tarihi");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell3.add(jLabel1);
        jLabel1.setBounds(130, 250, 170, 30);

        hastaKayitDogum_sec.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitDogum_sec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanell3.add(hastaKayitDogum_sec);
        hastaKayitDogum_sec.setBounds(330, 250, 140, 30);

        jPanell1.add(jPanell3);
        jPanell3.setBounds(20, 290, 680, 290);

        jPanell4.setBackground(new java.awt.Color(102, 255, 102));
        jPanell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell4.setLayout(null);

        jLabell9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell9.setForeground(new java.awt.Color(255, 0, 0));
        jLabell9.setText("    Hesap Oluşturmak İçin Gerekli Bilgiler");
        jLabell9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanell4.add(jLabell9);
        jLabell9.setBounds(175, 31, 261, 45);

        mail_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mail_labell.setForeground(new java.awt.Color(255, 0, 102));
        mail_labell.setText("Mail Adresi");
        mail_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanell4.add(mail_labell);
        mail_labell.setBounds(64, 94, 139, 36);

        jLabell10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell10.setForeground(new java.awt.Color(255, 0, 102));
        jLabell10.setText("Cep Telefon Numarası");
        jLabell10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanell4.add(jLabell10);
        jLabell10.setBounds(64, 150, 139, 36);

        parola_labell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        parola_labell.setForeground(new java.awt.Color(255, 0, 102));
        parola_labell.setText("Parola");
        parola_labell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanell4.add(parola_labell);
        parola_labell.setBounds(70, 300, 139, 36);

        jLabell11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell11.setForeground(new java.awt.Color(255, 0, 0));
        jLabell11.setText("Cep telefon numaranızı 0xxx xxx xx xx formatında giriniz.");
        jPanell4.add(jLabell11);
        jLabell11.setBounds(27, 195, 351, 15);

        hastaKayitMail_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaKayitMail_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitMail_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell4.add(hastaKayitMail_alani);
        hastaKayitMail_alani.setBounds(357, 95, 210, 36);

        hastaKayitCepTel_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaKayitCepTel_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitCepTel_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell4.add(hastaKayitCepTel_alani);
        hastaKayitCepTel_alani.setBounds(357, 149, 210, 40);

        hastaKayitParola_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaKayitParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanell4.add(hastaKayitParola_alani);
        hastaKayitParola_alani.setBounds(360, 300, 210, 36);

        jLabell12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabell12.setForeground(new java.awt.Color(255, 0, 102));
        jLabell12.setText("Adres");
        jLabell12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanell4.add(jLabell12);
        jLabell12.setBounds(68, 216, 130, 67);

        hastaKayitAdres_alani.setColumns(20);
        hastaKayitAdres_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaKayitAdres_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaKayitAdres_alani.setRows(5);
        hastaKayitAdres_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jScrollPane1.setViewportView(hastaKayitAdres_alani);

        jPanell4.add(jScrollPane1);
        jScrollPane1.setBounds(360, 210, 270, 95);

        mesaj_etiketi2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mesaj_etiketi2.setForeground(new java.awt.Color(255, 0, 0));
        jPanell4.add(mesaj_etiketi2);
        mesaj_etiketi2.setBounds(40, 350, 300, 22);

        jPanell1.add(jPanell4);
        jPanell4.setBounds(710, 290, 640, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanell1, javax.swing.GroupLayout.PREFERRED_SIZE, 1396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanell1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydet_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydet_butonuActionPerformed
        // TODO add your handling code here:
        if(hastaKayitTc_alani.getText().length()==0 || hastaKayitParola_alani.getPassword().toString().length()==0 || hastaKayitAd_alani.getText().length()==0 || hastaKayitSoyad_alani.getText().length()==0 || hastaKayitMail_alani.getText().length()==0 || hastaKayitCepTel_alani.getText().length()==0 || hastaKayitAdres_alani.getText().length()==0 || hastaKayitDogum_sec.getDate()==null ){
            YardimciMethotlar.mesajGoster("dolu");
        }
        else{
            String hastaTcNo = hastaKayitTc_alani.getText();
            String hastaParola = new String(hastaKayitParola_alani.getPassword());

            String hastaAdi = hastaKayitAd_alani.getText();
            String hastaSoyadi = hastaKayitSoyad_alani.getText();
            String hastaMail = hastaKayitMail_alani.getText();
            String hastaCepTel = hastaKayitCepTel_alani.getText();
            String hastaAdres = hastaKayitAdres_alani.getText();
            String cinsiyet = (String) hastaCinsiyetSec_alani.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy");
            String date = sdf.format(hastaKayitDogum_sec.getDate());//getDate kullanarak jdate den seçilen tarihi alabiliyorum 
            String date2 =sdf2.format(hastaKayitDogum_sec.getDate());
            
            int yil = Integer.valueOf(date2);
            int yas = simdikiYil-yil;//Otomatik hasta yaşını hesaplar
            //System.out.println(yas);
            String asilYas = String.valueOf(yas);
            if(hastaParola.length()<8 || hastaTcNo.length()!=11){
                if(hastaParola.length()<8){
                    mesaj_etiketi2.setText("Parola en az 8 karakterden oluşmalıdır!!!!!");

                }
                if(hastaTcNo.length()!=11){
                    mesaj_etiketi1.setText("Tc kimlik numarası 11 haneli olmalıdır!!");

                }
            }
            else{

                String kontrol = resepsiyonist.hastaKaydet(hastaTcNo, hastaParola, hastaAdi, hastaSoyadi,hastaMail,hastaCepTel,hastaAdres,cinsiyet,date,asilYas);
                if(kontrol == "true"){
                    YardimciMethotlar.mesajGoster("basarili");
                     ResepsiyonistEkrani res = new ResepsiyonistEkrani();
       
                     res.setVisible(true);
                     dispose();

                }
                else if(kontrol=="var"){
                    YardimciMethotlar.mesajGoster("Bu tc kimlik numaralı bir hasta zaten bulunmaktadır!!!");
                }
                else{
                    YardimciMethotlar.mesajGoster("hata");
                }

            }

        }

    }//GEN-LAST:event_kaydet_butonuActionPerformed

    private void temizle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizle_butonuActionPerformed
        // TODO add your handling code here:
        hastaKayitTc_alani.setText("");
        hastaKayitParola_alani.setText("");

        hastaKayitAd_alani.setText("");
        hastaKayitSoyad_alani.setText("");
        hastaKayitMail_alani.setText("");
        hastaKayitCepTel_alani.setText("");
        hastaKayitAdres_alani.setText("");
    }//GEN-LAST:event_temizle_butonuActionPerformed

    private void geri_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_butonuActionPerformed
        // TODO add your handling code here:
        ResepsiyonistEkrani res = new ResepsiyonistEkrani();
       
        res.setVisible(true);
        dispose();
    }//GEN-LAST:event_geri_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaKayitIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaKayitIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaKayitIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaKayitIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaKayitIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad_labell;
    private javax.swing.JLabel cinsiyet_labell;
    private javax.swing.JButton geri_butonu;
    private javax.swing.JComboBox<String> hastaCinsiyetSec_alani;
    private javax.swing.JTextField hastaKayitAd_alani;
    private javax.swing.JTextArea hastaKayitAdres_alani;
    private javax.swing.JTextField hastaKayitCepTel_alani;
    private com.toedter.calendar.JDateChooser hastaKayitDogum_sec;
    private javax.swing.JTextField hastaKayitMail_alani;
    private javax.swing.JPasswordField hastaKayitParola_alani;
    private javax.swing.JTextField hastaKayitSoyad_alani;
    private javax.swing.JTextField hastaKayitTc_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabell10;
    private javax.swing.JLabel jLabell11;
    private javax.swing.JLabel jLabell12;
    private javax.swing.JLabel jLabell5;
    private javax.swing.JLabel jLabell6;
    private javax.swing.JLabel jLabell7;
    private javax.swing.JLabel jLabell9;
    private javax.swing.JPanel jPanell1;
    private javax.swing.JPanel jPanell2;
    private javax.swing.JPanel jPanell3;
    private javax.swing.JPanel jPanell4;
    private javax.swing.JPanel jPanell5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydet_butonu;
    private javax.swing.JLabel kayit_resim2;
    private javax.swing.JLabel kimlik_labell;
    private javax.swing.JLabel mail_labell;
    private javax.swing.JLabel mesaj_etiketi1;
    private javax.swing.JLabel mesaj_etiketi2;
    private javax.swing.JLabel parola_labell;
    private javax.swing.JLabel soyad_labell;
    private javax.swing.JButton temizle_butonu;
    // End of variables declaration//GEN-END:variables
}
