/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Hasta;

/**
 *
 * @author İREM SAMUR
 */
public class HastaBilgileriniGoster extends javax.swing.JFrame {
    Hasta hasta = new Hasta();
    private String ad;
    private String soyad;
    private String hastaParola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;
    

    /**
     * Creates new form HastaBilgileriniGoster
     */
    public HastaBilgileriniGoster() {
        initComponents();
        ad = HastaIslemEkrani.hastaAdiniDondur();
        soyad = HastaIslemEkrani.hastaSoyadiniDondur();
        
        tcNo = HastaIslemEkrani.hastaTcNoDegeriDondur();
        
        mail = HastaIslemEkrani.hastaMailDondur();
        cepTel = HastaIslemEkrani.hastaCepTelDegeriDondur();
     
        adres = HastaIslemEkrani.hastaAdresDondur();
        cinsiyet = HastaIslemEkrani.hastaCinsiyetDondur();
        
        id = HastaIslemEkrani.hastaIdDegeriDondur();
        hastaParola = hasta.hastaParolaGetir(id);
        //System.out.println(hastaParola);
        
        bilgileriGoster();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanellll1 = new javax.swing.JPanel();
        cikisYap_butonu4 = new javax.swing.JButton();
        jLabelllll6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mailGoster_alani4 = new javax.swing.JLabel();
        telGoster_alani4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelllll5 = new javax.swing.JLabel();
        adGoster_alani4 = new javax.swing.JLabel();
        jLabelllll2 = new javax.swing.JLabel();
        soyadGoster_alani4 = new javax.swing.JLabel();
        jLabellll3 = new javax.swing.JLabel();
        kimlikNoGoster_alani4 = new javax.swing.JLabel();
        jLabellll4 = new javax.swing.JLabel();
        jLabelllll8 = new javax.swing.JLabel();
        adresGoster_alani4 = new javax.swing.JLabel();
        jLabelllll9 = new javax.swing.JLabel();
        cinsiyetGoster_alani4 = new javax.swing.JLabel();
        parolaGoster_alani5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTA BİLGİLERİNİ GÖSTER");

        jPanellll1.setBackground(new java.awt.Color(153, 255, 204));
        jPanellll1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 204, 0)), "Bilgilerimi Göster", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanellll1.setLayout(null);

        cikisYap_butonu4.setBackground(new java.awt.Color(255, 255, 0));
        cikisYap_butonu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cikisYap_butonu4.setForeground(new java.awt.Color(255, 51, 153));
        cikisYap_butonu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\unnamed_50x50.jpg")); // NOI18N
        cikisYap_butonu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        cikisYap_butonu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYap_butonu4ActionPerformed(evt);
            }
        });
        jPanellll1.add(cikisYap_butonu4);
        cikisYap_butonu4.setBounds(1250, 40, 70, 50);

        jLabelllll6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelllll6.setForeground(new java.awt.Color(255, 0, 0));
        jLabelllll6.setText("     Mail Adresi");
        jLabelllll6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanellll1.add(jLabelllll6);
        jLabelllll6.setBounds(680, 230, 170, 45);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Cep Telefon Numarası");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanellll1.add(jLabel7);
        jLabel7.setBounds(670, 330, 170, 45);

        mailGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mailGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        mailGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanellll1.add(mailGoster_alani4);
        mailGoster_alani4.setBounds(890, 230, 190, 50);

        telGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        telGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanellll1.add(telGoster_alani4);
        telGoster_alani4.setBounds(890, 330, 190, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\kisspng-computer-icons-printing-management-creative-busine-high-end-business-card-design-5adcaba622c989.0449529915244113021425_100x100.jpg")); // NOI18N
        jLabel1.setText("                         BİLGİLERİM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanellll1.add(jLabel1);
        jLabel1.setBounds(420, 40, 500, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255), 4));
        jPanel1.setLayout(null);

        jLabelllll5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelllll5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelllll5.setText("           Ad");
        jLabelllll5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabelllll5);
        jLabelllll5.setBounds(80, 50, 132, 45);

        adGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        adGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(adGoster_alani4);
        adGoster_alani4.setBounds(270, 50, 190, 50);

        jLabelllll2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelllll2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelllll2.setText("        Soyad");
        jLabelllll2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabelllll2);
        jLabelllll2.setBounds(80, 170, 132, 46);

        soyadGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soyadGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        soyadGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(soyadGoster_alani4);
        soyadGoster_alani4.setBounds(270, 170, 190, 50);

        jLabellll3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll3.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll3.setText("   Tc Kimlik No");
        jLabellll3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabellll3);
        jLabellll3.setBounds(80, 270, 132, 45);

        kimlikNoGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kimlikNoGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        kimlikNoGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(kimlikNoGoster_alani4);
        kimlikNoGoster_alani4.setBounds(270, 270, 190, 50);

        jLabellll4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll4.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll4.setText("        Parola");
        jLabellll4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabellll4);
        jLabellll4.setBounds(80, 370, 132, 48);

        jLabelllll8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelllll8.setForeground(new java.awt.Color(255, 0, 0));
        jLabelllll8.setText("              Adres");
        jLabelllll8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabelllll8);
        jLabelllll8.setBounds(550, 240, 170, 90);

        adresGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adresGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        adresGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(adresGoster_alani4);
        adresGoster_alani4.setBounds(770, 230, 190, 90);

        jLabelllll9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelllll9.setForeground(new java.awt.Color(255, 0, 0));
        jLabelllll9.setText("            Cinsiyet");
        jLabelllll9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabelllll9);
        jLabelllll9.setBounds(550, 370, 170, 45);

        cinsiyetGoster_alani4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinsiyetGoster_alani4.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetGoster_alani4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(cinsiyetGoster_alani4);
        cinsiyetGoster_alani4.setBounds(770, 370, 190, 50);

        parolaGoster_alani5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parolaGoster_alani5.setForeground(new java.awt.Color(255, 0, 0));
        parolaGoster_alani5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel1.add(parolaGoster_alani5);
        parolaGoster_alani5.setBounds(270, 370, 190, 50);

        jPanellll1.add(jPanel1);
        jPanel1.setBounds(120, 190, 1060, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanellll1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanellll1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void bilgileriGoster(){
        //System.out.println(cepTel);
        adGoster_alani4.setText(ad);
        soyadGoster_alani4.setText(soyad);
        parolaGoster_alani5.setText(hastaParola);
        kimlikNoGoster_alani4.setText(tcNo);
        mailGoster_alani4.setText(mail);
        telGoster_alani4.setText(cepTel);
        adresGoster_alani4.setText(adres);
        cinsiyetGoster_alani4.setText(cinsiyet);
       
    }
    private void cikisYap_butonu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYap_butonu4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cikisYap_butonu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaBilgileriniGoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adGoster_alani4;
    private javax.swing.JLabel adresGoster_alani4;
    private javax.swing.JButton cikisYap_butonu4;
    private javax.swing.JLabel cinsiyetGoster_alani4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabellll3;
    private javax.swing.JLabel jLabellll4;
    private javax.swing.JLabel jLabelllll2;
    private javax.swing.JLabel jLabelllll5;
    private javax.swing.JLabel jLabelllll6;
    private javax.swing.JLabel jLabelllll8;
    private javax.swing.JLabel jLabelllll9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanellll1;
    private javax.swing.JLabel kimlikNoGoster_alani4;
    private javax.swing.JLabel mailGoster_alani4;
    private javax.swing.JLabel parolaGoster_alani5;
    private javax.swing.JLabel soyadGoster_alani4;
    private javax.swing.JLabel telGoster_alani4;
    // End of variables declaration//GEN-END:variables
}
