/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Hasta;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class HastaBilgileriniGuncelle extends javax.swing.JFrame {
    Hasta hasta = new Hasta();
    private String ad;
    private String soyad;
    private String parola;
    private String tcNo;
    private int id;
    private String mail;
    private String cepTel;
    private String adres;
    private String cinsiyet;

    /**
     * Creates new form HastaBilgileriniGuncelle
     */
    public HastaBilgileriniGuncelle() {
        initComponents();
        ad = HastaIslemEkrani.hastaAdiniDondur();
        soyad = HastaIslemEkrani.hastaSoyadiniDondur();
        
        tcNo = HastaIslemEkrani.hastaTcNoDegeriDondur();
        
        mail = HastaIslemEkrani.hastaMailDondur();
        cepTel = HastaIslemEkrani.hastaCepTelDegeriDondur();
     
        adres = HastaIslemEkrani.hastaAdresDondur();
        cinsiyet = HastaIslemEkrani.hastaCinsiyetDondur();
        
        id = HastaIslemEkrani.hastaIdDegeriDondur();
        parola = hasta.hastaParolaGetir(id);
        hastaAd_guncelle.setText(ad);
        hastaSoyad_guncelle.setText(soyad);
        hastaParola_guncelle.setText(parola);
        hastaTc_guncelle.setText(tcNo);
        hastaMail_guncelle.setText(mail);
        hastaTel_guncelle.setText(cepTel);
        hastaAdres_guncelle.setText(adres);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelll2 = new javax.swing.JPanel();
        mesaj_etiketi = new javax.swing.JLabel();
        mesaj_etiketi2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hastaAdres_guncelle = new javax.swing.JTextArea();
        hastaTel_guncelle = new javax.swing.JTextField();
        hastaMail_guncelle = new javax.swing.JTextField();
        jLabellll11 = new javax.swing.JLabel();
        jLabellll10 = new javax.swing.JLabel();
        jLabellll9 = new javax.swing.JLabel();
        hastaParola_guncelle = new javax.swing.JTextField();
        jLabellll6 = new javax.swing.JLabel();
        hastaTc_guncelle = new javax.swing.JTextField();
        jLabellll5 = new javax.swing.JLabel();
        hastaSoyad_guncelle = new javax.swing.JTextField();
        jLabellll4 = new javax.swing.JLabel();
        hastaAd_guncelle = new javax.swing.JTextField();
        jLabellll8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iptal_butonu3 = new javax.swing.JButton();
        bilgiGuncelle_butonu3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTA BİLGİLERİNİ GÜNCELLE");

        jPanelll2.setBackground(new java.awt.Color(102, 255, 204));
        jPanelll2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4), "Bilgilerimi Güncelle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 102))); // NOI18N
        jPanelll2.setLayout(null);
        jPanelll2.add(mesaj_etiketi);
        mesaj_etiketi.setBounds(180, 290, 220, 30);
        jPanelll2.add(mesaj_etiketi2);
        mesaj_etiketi2.setBounds(180, 410, 200, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.setLayout(null);

        hastaAdres_guncelle.setColumns(20);
        hastaAdres_guncelle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hastaAdres_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaAdres_guncelle.setRows(5);
        hastaAdres_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jScrollPane1.setViewportView(hastaAdres_guncelle);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(950, 290, 180, 110);

        hastaTel_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaTel_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaTel_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaTel_guncelle);
        hastaTel_guncelle.setBounds(940, 190, 186, 49);

        hastaMail_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaMail_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaMail_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaMail_guncelle);
        hastaMail_guncelle.setBounds(940, 80, 186, 49);

        jLabellll11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll11.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll11.setText("               Adres");
        jLabellll11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll11);
        jLabellll11.setBounds(670, 300, 180, 110);

        jLabellll10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll10.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll10.setText("Cep Telefon Numarası");
        jLabellll10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll10);
        jLabellll10.setBounds(670, 190, 180, 49);

        jLabellll9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll9.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll9.setText("        Mail Adresi");
        jLabellll9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll9);
        jLabellll9.setBounds(670, 80, 180, 49);

        hastaParola_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaParola_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaParola_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaParola_guncelle);
        hastaParola_guncelle.setBounds(380, 360, 186, 49);

        jLabellll6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll6.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll6.setText("                 Parola");
        jLabellll6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll6);
        jLabellll6.setBounds(120, 360, 205, 49);

        hastaTc_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaTc_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaTc_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaTc_guncelle);
        hastaTc_guncelle.setBounds(380, 250, 186, 49);

        jLabellll5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll5.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll5.setText("               Tc Kimlik No");
        jLabellll5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll5);
        jLabellll5.setBounds(120, 240, 205, 49);

        hastaSoyad_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaSoyad_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaSoyad_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaSoyad_guncelle);
        hastaSoyad_guncelle.setBounds(380, 140, 186, 49);

        jLabellll4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll4.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll4.setText("                     Soyad");
        jLabellll4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll4);
        jLabellll4.setBounds(120, 140, 205, 49);

        hastaAd_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaAd_guncelle.setForeground(new java.awt.Color(255, 0, 0));
        hastaAd_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.add(hastaAd_guncelle);
        hastaAd_guncelle.setBounds(380, 50, 186, 49);

        jLabellll8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellll8.setForeground(new java.awt.Color(255, 0, 0));
        jLabellll8.setText("                      Ad");
        jLabellll8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel1.add(jLabellll8);
        jLabellll8.setBounds(130, 50, 205, 49);

        jPanelll2.add(jPanel1);
        jPanel1.setBounds(80, 120, 1210, 440);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153), 4));
        jPanel2.setLayout(null);

        iptal_butonu3.setBackground(new java.awt.Color(102, 255, 204));
        iptal_butonu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iptal_butonu3.setForeground(new java.awt.Color(255, 0, 102));
        iptal_butonu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        iptal_butonu3.setText("İptal Et");
        iptal_butonu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        iptal_butonu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptal_butonu3ActionPerformed(evt);
            }
        });
        jPanel2.add(iptal_butonu3);
        iptal_butonu3.setBounds(470, 30, 170, 50);

        bilgiGuncelle_butonu3.setBackground(new java.awt.Color(102, 255, 204));
        bilgiGuncelle_butonu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilgiGuncelle_butonu3.setForeground(new java.awt.Color(255, 0, 102));
        bilgiGuncelle_butonu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\191-1918674_colour-change-icon-hd-png-download_50x50.jpg")); // NOI18N
        bilgiGuncelle_butonu3.setText("Güncelle");
        bilgiGuncelle_butonu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        bilgiGuncelle_butonu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiGuncelle_butonu3ActionPerformed(evt);
            }
        });
        jPanel2.add(bilgiGuncelle_butonu3);
        bilgiGuncelle_butonu3.setBounds(190, 30, 170, 50);

        jPanelll2.add(jPanel2);
        jPanel2.setBounds(320, 580, 750, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelll2, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelll2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgiGuncelle_butonu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiGuncelle_butonu3ActionPerformed
        // TODO add your handling code here:
        String yeniAd =  hastaAd_guncelle.getText();
        String yeniSoyad = hastaSoyad_guncelle.getText();
        String yeniParola = hastaParola_guncelle.getText();
        String yeniTcNo = hastaTc_guncelle.getText();
        String yeniMail = hastaMail_guncelle.getText();
        String yeniCepTel = hastaTel_guncelle.getText();
        String yeniAdres = hastaAdres_guncelle.getText();
       
        if(hastaAd_guncelle.getText().length()==0 || hastaSoyad_guncelle.getText().length()==0 || hastaParola_guncelle.getText().length()==0 || hastaTc_guncelle.getText().length()==0 || hastaMail_guncelle.getText().length()==0 || hastaTel_guncelle.getText().length()==0 || hastaAdres_guncelle.getText().length()==0 ){
            YardimciMethotlar.mesajGoster("dolu");
        }
        else{

            if(yeniParola.length()<8 || yeniTcNo.length()!=11){
                if(yeniParola.length()<8){
                    mesaj_etiketi2.setText("Parolanız en az 8 haneli olmalıdır !!!");

                }
                if(yeniTcNo.length()!=11){
                    mesaj_etiketi.setText("Tc kimlik numarası 11 hane dışında olamaz!!!");

                }

            }
            else{
                boolean kontrol = hasta.hastaBilgileriniGuncelle(id, yeniAd,yeniSoyad, yeniTcNo, yeniParola,yeniMail,yeniCepTel,yeniAdres);
                if(kontrol){
                    YardimciMethotlar.mesajGoster("basarili");
                }
                else{
                    YardimciMethotlar.mesajGoster("error");
                }

            }

        }
    }//GEN-LAST:event_bilgiGuncelle_butonu3ActionPerformed

    private void iptal_butonu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptal_butonu3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_iptal_butonu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaBilgileriniGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaBilgileriniGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgiGuncelle_butonu3;
    private javax.swing.JTextField hastaAd_guncelle;
    private javax.swing.JTextArea hastaAdres_guncelle;
    private javax.swing.JTextField hastaMail_guncelle;
    private javax.swing.JTextField hastaParola_guncelle;
    private javax.swing.JTextField hastaSoyad_guncelle;
    private javax.swing.JTextField hastaTc_guncelle;
    private javax.swing.JTextField hastaTel_guncelle;
    private javax.swing.JButton iptal_butonu3;
    private javax.swing.JLabel jLabellll10;
    private javax.swing.JLabel jLabellll11;
    private javax.swing.JLabel jLabellll4;
    private javax.swing.JLabel jLabellll5;
    private javax.swing.JLabel jLabellll6;
    private javax.swing.JLabel jLabellll8;
    private javax.swing.JLabel jLabellll9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelll2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_etiketi;
    private javax.swing.JLabel mesaj_etiketi2;
    // End of variables declaration//GEN-END:variables
}
