/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Hasta;
import com.irem.veritabani.YardimciMethotlar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author İREM SAMUR
 */
public class HastaKayitEkrani extends javax.swing.JFrame {
    private Hasta hasta = new Hasta();
     Date simdikiZaman = new Date();
        
     DateFormat df = new SimpleDateFormat("yyyy");
        
     private String tarih = df.format(simdikiZaman);
     private int simdikiYil = Integer.valueOf(tarih);

    /**
     * Creates new form HastaKayitEkrani
     */
    public HastaKayitEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kayit_resim = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ad_label = new javax.swing.JLabel();
        soyad_label = new javax.swing.JLabel();
        kimlik_label = new javax.swing.JLabel();
        hastaAd_alani = new javax.swing.JTextField();
        hastaSoyad_alani = new javax.swing.JTextField();
        hastaTc_alani = new javax.swing.JTextField();
        cinsiyet_label = new javax.swing.JLabel();
        cinsiyetSec_alani = new javax.swing.JComboBox<>();
        mesaj_etiketi1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hastaDogumTarihi_sec = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        mail_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        parola_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hastaMail_alani = new javax.swing.JTextField();
        hastaCepTel_alani = new javax.swing.JTextField();
        hastaParola_alani = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hastaAdres_alani = new javax.swing.JTextArea();
        mesaj_etiketi2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        kaydol_butonu = new javax.swing.JButton();
        bilgileri_temizle = new javax.swing.JButton();
        iptalEt_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTA KAYIT EKRANI");

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 0, 102)), "Hasta Kayıt Ekranı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 4));
        jPanel2.setLayout(null);

        kayit_resim.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\register_200x200.jpg")); // NOI18N
        kayit_resim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4));
        jPanel2.add(kayit_resim);
        kayit_resim.setBounds(390, 10, 208, 191);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("                          HASTA HESABI KAYIT EKRANI");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(630, 70, 500, 65);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Hesap oluşturup, kaydınızı tamamlamak için lütfen aşağıdaki bilgilerin tamamını doldurunuz. (Tüm bilgilerin doldurulması zorunludur.)");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 210, 842, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 1290, 254);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("                       Kişisel Bilgiler");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(226, 24, 281, 35);

        ad_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ad_label.setForeground(new java.awt.Color(255, 0, 102));
        ad_label.setText("      Ad");
        ad_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(ad_label);
        ad_label.setBounds(20, 80, 110, 40);

        soyad_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        soyad_label.setForeground(new java.awt.Color(255, 0, 102));
        soyad_label.setText("   Soyad");
        soyad_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(soyad_label);
        soyad_label.setBounds(20, 150, 89, 38);

        kimlik_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kimlik_label.setForeground(new java.awt.Color(255, 0, 102));
        kimlik_label.setText("Tc Kimlik No");
        kimlik_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(kimlik_label);
        kimlik_label.setBounds(370, 80, 89, 38);

        hastaAd_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaAd_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaAd_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanel3.add(hastaAd_alani);
        hastaAd_alani.setBounds(180, 80, 128, 40);

        hastaSoyad_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaSoyad_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaSoyad_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanel3.add(hastaSoyad_alani);
        hastaSoyad_alani.setBounds(180, 150, 128, 38);

        hastaTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanel3.add(hastaTc_alani);
        hastaTc_alani.setBounds(490, 80, 161, 38);

        cinsiyet_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cinsiyet_label.setForeground(new java.awt.Color(255, 0, 102));
        cinsiyet_label.setText("   Cinsiyet");
        cinsiyet_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(cinsiyet_label);
        cinsiyet_label.setBounds(370, 150, 84, 37);

        cinsiyetSec_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cinsiyetSec_alani.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetSec_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kadın", "Erkek", "Diğer" }));
        cinsiyetSec_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));
        jPanel3.add(cinsiyetSec_alani);
        cinsiyetSec_alani.setBounds(490, 150, 161, 37);

        mesaj_etiketi1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mesaj_etiketi1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(mesaj_etiketi1);
        mesaj_etiketi1.setBounds(360, 150, 290, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Doğum Tarihi");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(140, 210, 110, 40);

        hastaDogumTarihi_sec.setForeground(new java.awt.Color(255, 0, 0));
        hastaDogumTarihi_sec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(hastaDogumTarihi_sec);
        hastaDogumTarihi_sec.setBounds(290, 210, 150, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 290, 680, 270);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("    Hesap Oluşturmak İçin Gerekli Bilgiler");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 4));
        jPanel4.add(jLabel9);
        jLabel9.setBounds(175, 31, 261, 45);

        mail_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mail_label.setForeground(new java.awt.Color(255, 0, 102));
        mail_label.setText("Mail Adresi");
        mail_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel4.add(mail_label);
        mail_label.setBounds(64, 94, 139, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("Cep Telefon Numarası");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanel4.add(jLabel10);
        jLabel10.setBounds(64, 150, 139, 36);

        parola_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        parola_label.setForeground(new java.awt.Color(255, 0, 102));
        parola_label.setText("Parola");
        parola_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 4));
        jPanel4.add(parola_label);
        parola_label.setBounds(70, 300, 139, 36);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Cep telefon numaranızı 0xxx xxx xx xx formatında giriniz.");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(27, 195, 351, 15);

        hastaMail_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaMail_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaMail_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel4.add(hastaMail_alani);
        hastaMail_alani.setBounds(357, 95, 210, 36);

        hastaCepTel_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaCepTel_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaCepTel_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel4.add(hastaCepTel_alani);
        hastaCepTel_alani.setBounds(357, 149, 210, 40);

        hastaParola_alani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hastaParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jPanel4.add(hastaParola_alani);
        hastaParola_alani.setBounds(360, 300, 210, 36);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jLabel12.setText("Adres");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(68, 216, 130, 67);

        hastaAdres_alani.setColumns(20);
        hastaAdres_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hastaAdres_alani.setForeground(new java.awt.Color(255, 0, 0));
        hastaAdres_alani.setRows(5);
        hastaAdres_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        jScrollPane1.setViewportView(hastaAdres_alani);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(360, 210, 270, 95);

        mesaj_etiketi2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mesaj_etiketi2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(mesaj_etiketi2);
        mesaj_etiketi2.setBounds(40, 350, 300, 22);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(710, 290, 640, 390);

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));

        kaydol_butonu.setBackground(new java.awt.Color(153, 255, 204));
        kaydol_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kaydol_butonu.setForeground(new java.awt.Color(255, 0, 204));
        kaydol_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\83006249_50x50.jpg")); // NOI18N
        kaydol_butonu.setText("Kaydol");
        kaydol_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        kaydol_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydol_butonuActionPerformed(evt);
            }
        });

        bilgileri_temizle.setBackground(new java.awt.Color(153, 255, 204));
        bilgileri_temizle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilgileri_temizle.setForeground(new java.awt.Color(255, 0, 204));
        bilgileri_temizle.setText("Bilgileri Temizle");
        bilgileri_temizle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        bilgileri_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgileri_temizleActionPerformed(evt);
            }
        });

        iptalEt_butonu.setBackground(new java.awt.Color(153, 255, 204));
        iptalEt_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iptalEt_butonu.setForeground(new java.awt.Color(255, 0, 204));
        iptalEt_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        iptalEt_butonu.setText("İptal Et");
        iptalEt_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        iptalEt_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalEt_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kaydol_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bilgileri_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(iptalEt_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydol_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilgileri_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iptalEt_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 570, 680, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iptalEt_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptalEt_butonuActionPerformed
        // TODO add your handling code here:
        YardimciMethotlar.onay("eminim");
        YardimciMethotlar.yonlendirmeMesajiVer("Anasayfaya yönlendiriliyorsunuz....");
        dispose();
        AnaEkran anaEkran = new AnaEkran();
        anaEkran.setVisible(true);
        
        
    }//GEN-LAST:event_iptalEt_butonuActionPerformed

    private void kaydol_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydol_butonuActionPerformed
        // TODO add your handling code here:
        if(hastaTc_alani.getText().length()==0 || hastaParola_alani.getPassword().toString().length()==0 || hastaAd_alani.getText().length()==0 || hastaSoyad_alani.getText().length()==0 || hastaMail_alani.getText().length()==0 || hastaCepTel_alani.getText().length()==0 || hastaAdres_alani.getText().length()==0 || hastaDogumTarihi_sec.getDate()==null ){
            YardimciMethotlar.mesajGoster("dolu");
        }
        else{
            String hastaTcNo = hastaTc_alani.getText();
            String hastaParola = new String(hastaParola_alani.getPassword());
            
            String hastaAdi = hastaAd_alani.getText();
            String hastaSoyadi = hastaSoyad_alani.getText();
            String hastaMail = hastaMail_alani.getText();
            String hastaCepTel = hastaCepTel_alani.getText();
            String hastaAdres = hastaAdres_alani.getText();
            String cinsiyet = (String) cinsiyetSec_alani.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");//şuan içinde bulunduğumuz tarihi alır
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy");
            String date = sdf.format(hastaDogumTarihi_sec.getDate());//getDate kullanarak jdate den seçilen tarihi alabiliyorum 
            String date2 =sdf2.format(hastaDogumTarihi_sec.getDate());
            int yil = Integer.valueOf(date2);
            int yas = simdikiYil-yil;//simdiki yil degerinden hasta nın seçtiği doğum tarihini çıkararak hastanın yaşını hesaplar
            //Hasta sisteme kaydolurken yaşı otomatik hesaplanır
            //System.out.println(yas);
            String asilYas = String.valueOf(yas);
            if(hastaParola.length()<8 || hastaTcNo.length()!=11){
                if(hastaParola.length()<8){
                    mesaj_etiketi2.setText("Parola en az 8 karakterden oluşmalıdır!!!!!");
                    
                }
                if(hastaTcNo.length()!=11){
                    mesaj_etiketi1.setText("Tc kimlik numarası 11 haneli olmalıdır!!");
                    
                }
            }
            else{
                
                 String kontrol = hasta.kaydol(hastaTcNo, hastaParola, hastaAdi, hastaSoyadi,hastaMail,hastaCepTel,hastaAdres,cinsiyet,date,asilYas);//hasta classı içindeki kaydol methodunu çağırarak hastanın veritabanına kaydını yapar
                 if(kontrol == "true"){
                    YardimciMethotlar.mesajGoster("basarili");
                    AnaEkran anaEkran = new AnaEkran();
                    anaEkran.setVisible(true);
                    dispose();
                
            }
                else if(kontrol=="var"){
                    YardimciMethotlar.mesajGoster("Bu tc kimlik numaralı bir hasta zaten bulunmaktadır!!!");
                    //Aynı tc kimlik no lu hastaların eklenmesini engeller
            }
                else{
                    YardimciMethotlar.mesajGoster("hata");
            }
                
            }
            
           
            
        }
        
    }//GEN-LAST:event_kaydol_butonuActionPerformed

    private void bilgileri_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgileri_temizleActionPerformed
        // TODO add your handling code here:
        //Bu butona basılınca bilgi alanlarının temizlenmesini sağlar
        hastaTc_alani.setText("");
        hastaParola_alani.setText("");
            
         hastaAd_alani.setText("");
         hastaSoyad_alani.setText("");
         hastaMail_alani.setText("");
         hastaCepTel_alani.setText("");
        hastaAdres_alani.setText("");
    }//GEN-LAST:event_bilgileri_temizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaKayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad_label;
    private javax.swing.JButton bilgileri_temizle;
    private javax.swing.JComboBox<String> cinsiyetSec_alani;
    private javax.swing.JLabel cinsiyet_label;
    private javax.swing.JTextField hastaAd_alani;
    private javax.swing.JTextArea hastaAdres_alani;
    private javax.swing.JTextField hastaCepTel_alani;
    private com.toedter.calendar.JDateChooser hastaDogumTarihi_sec;
    private javax.swing.JTextField hastaMail_alani;
    private javax.swing.JPasswordField hastaParola_alani;
    private javax.swing.JTextField hastaSoyad_alani;
    private javax.swing.JTextField hastaTc_alani;
    private javax.swing.JButton iptalEt_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydol_butonu;
    private javax.swing.JLabel kayit_resim;
    private javax.swing.JLabel kimlik_label;
    private javax.swing.JLabel mail_label;
    private javax.swing.JLabel mesaj_etiketi1;
    private javax.swing.JLabel mesaj_etiketi2;
    private javax.swing.JLabel parola_label;
    private javax.swing.JLabel soyad_label;
    // End of variables declaration//GEN-END:variables
}
