/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Resepsiyonist;
import com.irem.models.User;

/**
 *
 * @author İREM SAMUR
 */
public class ResepsiyonistEkrani extends javax.swing.JFrame {
    private static Resepsiyonist resepsiyonist = new Resepsiyonist();
    User user = new Resepsiyonist();//polimorfizim uyguladık
    //Bu sayede aralarında inheritance bulunan User üst classı ve Resepsiyonist alt classını
    //kullanarak User classından nesne oluşturup, Resepsiyonist classı ile constructor'ını oluşturarak
    //Repseisyonist içinde override edilmiş methodu User ile çağırdık
    private String isim;

    /**
     * Creates new form ResepsiyonistEkrani
     */
    public ResepsiyonistEkrani(Resepsiyonist resepsiyonist) {
        initComponents();
        isim = resepsiyonist.getAd()+" "+resepsiyonist.getSoyad();
        user.girisMesajiYaz(isim);//polimorfizim sayesinde üst classın user'ın methodunu resepsiyonist classında override ederek
        //üst classdan oluşturulan nesne ile kullandık
    }
    public ResepsiyonistEkrani(){
          initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cikisYap_butonu2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hastaKayit_butonu = new javax.swing.JButton();
        hastaRandevu_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESEPSİYONİST EKRANI");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(null);

        cikisYap_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\4700771_exit-power-off-icon-white-hd-png-download_50x50.jpg")); // NOI18N
        cikisYap_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYap_butonu2ActionPerformed(evt);
            }
        });
        jPanel1.add(cikisYap_butonu2);
        cikisYap_butonu2.setBounds(1280, 20, 57, 59);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\hospital-reception-11-641121.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 140, 640, 410);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("                      RESEPSİYONİST EKRANI");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 4));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 50, 480, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.setLayout(null);

        hastaKayit_butonu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hastaKayit_butonu.setForeground(new java.awt.Color(255, 51, 102));
        hastaKayit_butonu.setText("Hasta Kayıt İşlemleri");
        hastaKayit_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        hastaKayit_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaKayit_butonuActionPerformed(evt);
            }
        });
        jPanel2.add(hastaKayit_butonu);
        hastaKayit_butonu.setBounds(450, 20, 319, 57);

        hastaRandevu_butonu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hastaRandevu_butonu.setForeground(new java.awt.Color(255, 51, 153));
        hastaRandevu_butonu.setText("Hasta Muayene Randevu İşlemleri");
        hastaRandevu_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        hastaRandevu_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaRandevu_butonuActionPerformed(evt);
            }
        });
        jPanel2.add(hastaRandevu_butonu);
        hastaRandevu_butonu.setBounds(50, 20, 319, 59);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 570, 850, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hastaKayit_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaKayit_butonuActionPerformed
        // TODO add your handling code here:
        HastaKayitIslemleri hastaKayit = new HastaKayitIslemleri();
        hastaKayit.setVisible(true);
        dispose();
    }//GEN-LAST:event_hastaKayit_butonuActionPerformed

    private void hastaRandevu_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaRandevu_butonuActionPerformed
        // TODO add your handling code here:
         HastaRandevuOlusturEkrani hastarandevu = new HastaRandevuOlusturEkrani();
         hastarandevu.setVisible(true);
         dispose();
    }//GEN-LAST:event_hastaRandevu_butonuActionPerformed

    private void cikisYap_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYap_butonu2ActionPerformed
        // TODO add your handling code here:
        AnaEkran ana = new AnaEkran();
        ana.setVisible(true);
        dispose();
    }//GEN-LAST:event_cikisYap_butonu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepsiyonistEkrani(resepsiyonist).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikisYap_butonu2;
    private javax.swing.JButton hastaKayit_butonu;
    private javax.swing.JButton hastaRandevu_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
