/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.YoneticiIslemleri;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class ResepsiyonistEkle extends javax.swing.JFrame {
    YoneticiIslemleri yoneticiIslem = new YoneticiIslemleri();
    //Kaydı yapılacak resepsiyonist için otomatik 8 haneli geçici rastgele şifre üretir
    private long parola = 10000000+(int)(Math.random()* 90000000);
    private String parola2 = String.valueOf(parola);

    /**
     * Creates new form ResepsiyonistEkle
     */
    public ResepsiyonistEkle() {
        initComponents();
        resepsiyonistParola_alani.setText(parola2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        geri_butonu4 = new javax.swing.JButton();
        mesaj_etiketi1 = new javax.swing.JLabel();
        mesaj_etiketi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resepsiyonistAdres_alani = new javax.swing.JTextArea();
        resepsiyonistCep_alani = new javax.swing.JTextField();
        resepsiyonistMail_alani = new javax.swing.JTextField();
        cinsiyetSec_box2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resepsiyonistParola_alani = new javax.swing.JTextField();
        resepsiyonistSoyad_alani = new javax.swing.JTextField();
        resepsiyonistAd_alani = new javax.swing.JTextField();
        resepsiyonistTc_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        atamaIptali_butonu4 = new javax.swing.JButton();
        resepsiyonistEkle_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESEPSİYONİST EKLE ");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("            Soyad");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 370, 160, 50);

        geri_butonu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\back-158491_1280_50x50.jpg")); // NOI18N
        geri_butonu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        geri_butonu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_butonu4ActionPerformed(evt);
            }
        });
        jPanel1.add(geri_butonu4);
        geri_butonu4.setBounds(1280, 20, 59, 60);
        jPanel1.add(mesaj_etiketi1);
        mesaj_etiketi1.setBounds(110, 180, 300, 20);
        jPanel1.add(mesaj_etiketi);
        mesaj_etiketi.setBounds(110, 404, 320, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("      RESEPSİYONİST EKLEME EKRANI");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 30, 410, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel2.setLayout(null);

        resepsiyonistAdres_alani.setColumns(20);
        resepsiyonistAdres_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistAdres_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistAdres_alani.setRows(5);
        resepsiyonistAdres_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jScrollPane1.setViewportView(resepsiyonistAdres_alani);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(810, 320, 220, 90);

        resepsiyonistCep_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistCep_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistCep_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        resepsiyonistCep_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepsiyonistCep_alaniActionPerformed(evt);
            }
        });
        jPanel2.add(resepsiyonistCep_alani);
        resepsiyonistCep_alani.setBounds(810, 250, 220, 40);

        resepsiyonistMail_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistMail_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistMail_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(resepsiyonistMail_alani);
        resepsiyonistMail_alani.setBounds(810, 180, 220, 40);

        cinsiyetSec_box2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cinsiyetSec_box2.setForeground(new java.awt.Color(255, 0, 0));
        cinsiyetSec_box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Cinsiyet Seç--", "Kadın", "Erkek", "Diğer", " " }));
        cinsiyetSec_box2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(cinsiyetSec_box2);
        cinsiyetSec_box2.setBounds(810, 90, 220, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("           Cinsiyet ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(500, 90, 200, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("         Mail Adresi");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(500, 180, 200, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("     Cep Telefon Numarası");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(500, 250, 200, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("        Adres");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(500, 330, 200, 80);

        resepsiyonistParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(resepsiyonistParola_alani);
        resepsiyonistParola_alani.setBounds(260, 350, 160, 40);

        resepsiyonistSoyad_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistSoyad_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistSoyad_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(resepsiyonistSoyad_alani);
        resepsiyonistSoyad_alani.setBounds(260, 260, 160, 50);

        resepsiyonistAd_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistAd_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistAd_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(resepsiyonistAd_alani);
        resepsiyonistAd_alani.setBounds(260, 180, 160, 50);

        resepsiyonistTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        resepsiyonistTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel2.add(resepsiyonistTc_alani);
        resepsiyonistTc_alani.setBounds(260, 80, 160, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("          Parola");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 350, 160, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("             Ad");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 180, 160, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("        Tc Kimlik No");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 80, 159, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 110, 1150, 450);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel3.setLayout(null);

        atamaIptali_butonu4.setBackground(new java.awt.Color(255, 255, 255));
        atamaIptali_butonu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atamaIptali_butonu4.setForeground(new java.awt.Color(204, 0, 102));
        atamaIptali_butonu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        atamaIptali_butonu4.setText("İptal Et");
        atamaIptali_butonu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        atamaIptali_butonu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atamaIptali_butonu4ActionPerformed(evt);
            }
        });
        jPanel3.add(atamaIptali_butonu4);
        atamaIptali_butonu4.setBounds(500, 20, 170, 60);

        resepsiyonistEkle_butonu.setBackground(new java.awt.Color(255, 255, 255));
        resepsiyonistEkle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistEkle_butonu.setForeground(new java.awt.Color(204, 0, 102));
        resepsiyonistEkle_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\112-1123853_group-demos-access-user-icon_50x50.jpg")); // NOI18N
        resepsiyonistEkle_butonu.setText("Resepsiyonist Ekle");
        resepsiyonistEkle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        resepsiyonistEkle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepsiyonistEkle_butonuActionPerformed(evt);
            }
        });
        jPanel3.add(resepsiyonistEkle_butonu);
        resepsiyonistEkle_butonu.setBounds(120, 20, 220, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(280, 580, 710, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resepsiyonistEkle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepsiyonistEkle_butonuActionPerformed
        // TODO add your handling code here:
        if(resepsiyonistTc_alani.getText().length()==0 || resepsiyonistParola_alani.getText().length()==0 || resepsiyonistAd_alani.getText().length()==0 || resepsiyonistSoyad_alani.getText().length()==0 || resepsiyonistMail_alani.getText().length()==0 || resepsiyonistCep_alani.getText().length()==0 || resepsiyonistAdres_alani.getText().length()==0 || cinsiyetSec_box2.getSelectedIndex()==0  ){
            YardimciMethotlar.mesajGoster("dolu");
        }
        else{
            String tc = resepsiyonistTc_alani.getText();
            String sifre = resepsiyonistParola_alani.getText();
            String ad = resepsiyonistAd_alani.getText();
            String soyad = resepsiyonistSoyad_alani.getText();
            String mail = resepsiyonistMail_alani.getText();
            String cepTel = resepsiyonistCep_alani.getText();
            String adres = resepsiyonistAdres_alani.getText();
            String cinsiyet = (String) cinsiyetSec_box2.getSelectedItem();
             if(resepsiyonistParola_alani.getText().length()<8 || resepsiyonistTc_alani.getText().length()!=11){
                if(sifre.length()<8){
                    mesaj_etiketi.setText("Parola en az 8 karakterden oluşmalıdır!!!!!");
                    
                }
                if(tc.length()!=11){
                    mesaj_etiketi1.setText("Tc kimlik numarası 11 haneli olmalıdır!!");
                    
                }
            }
             else{
                 
                    boolean durum = yoneticiIslem.resepsiyonistEkle(tc, sifre, ad, soyad, mail, cepTel, adres, cinsiyet);
                    if(durum){
                      YardimciMethotlar.mesajGoster("basarili");
        }
                    else{
                      YardimciMethotlar.mesajGoster("hata");
        }
                 
             }
            
        }
     
        
     
    }//GEN-LAST:event_resepsiyonistEkle_butonuActionPerformed

    private void atamaIptali_butonu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atamaIptali_butonu4ActionPerformed
        // TODO add your handling code here:
        YardimciMethotlar.mesajGoster("eminim");
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
    }//GEN-LAST:event_atamaIptali_butonu4ActionPerformed

    private void geri_butonu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_butonu4ActionPerformed
        // TODO add your handling code here:
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();

    }//GEN-LAST:event_geri_butonu4ActionPerformed

    private void resepsiyonistCep_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepsiyonistCep_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resepsiyonistCep_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonistEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepsiyonistEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atamaIptali_butonu4;
    private javax.swing.JComboBox<String> cinsiyetSec_box2;
    private javax.swing.JButton geri_butonu4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_etiketi;
    private javax.swing.JLabel mesaj_etiketi1;
    private javax.swing.JTextField resepsiyonistAd_alani;
    private javax.swing.JTextArea resepsiyonistAdres_alani;
    private javax.swing.JTextField resepsiyonistCep_alani;
    private javax.swing.JButton resepsiyonistEkle_butonu;
    private javax.swing.JTextField resepsiyonistMail_alani;
    private javax.swing.JTextField resepsiyonistParola_alani;
    private javax.swing.JTextField resepsiyonistSoyad_alani;
    private javax.swing.JTextField resepsiyonistTc_alani;
    // End of variables declaration//GEN-END:variables
}
