/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.YoneticiIslemleri;
import com.irem.models.Yoneticiler;
import com.irem.veritabani.YardimciMethotlar;

/**
 *
 * @author İREM SAMUR
 */
public class YoneticiBilgileriGuncelle extends javax.swing.JFrame {
    YoneticiIslemleri yonetici = new YoneticiIslemleri();
    Yoneticiler yoneticiler = new Yoneticiler();
    private String ad;
    private String soyad;
    private String tc;
    private String yoneticiParola;
    private String mail;
    private String cep;
    private String adres;
    private String cinsiyet;
    private int id;

    /**
     * Creates new form YoneticiBilgileriGuncelle
     */
    public YoneticiBilgileriGuncelle() {
        initComponents();
        id = YoneticiAnaEkrani.idDondur();
        tc = YoneticiAnaEkrani.tcNoDondur();
        guncelleTc_alani.setText(tc);
        ad = YoneticiAnaEkrani.yoneticiAdiDondur();
        guncelleAd_alani.setText(ad);
        soyad = YoneticiAnaEkrani.yoneticiSoyadiDondur();
        guncelleSoyad_alani.setText(soyad);
        
        mail = YoneticiAnaEkrani.mailDondur();
        guncelleMail_alani.setText(mail);
        cep = YoneticiAnaEkrani.ceptelDondur();
        guncelleCep_alani.setText(cep);
        adres = YoneticiAnaEkrani.adresDondur();
        guncelleAdres_alani.setText(adres);
        yoneticiParola = yoneticiler.parolaGetir(id);
        guncelleParola_alani.setText(yoneticiParola);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        geri_butonu2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        guncelleMail_alani = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        guncelleCep_alani = new javax.swing.JTextField();
        guncelleParola_alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guncelleAdres_alani = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        guncelleSoyad_alani = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        guncelleAd_alani = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        guncelleTc_alani = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Iptal_butonu = new javax.swing.JButton();
        bilgiGuncelle_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YÖNETİCİ BİLGİLERİNİ GÜNCELLE");

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.setLayout(null);

        geri_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\back-158491_1280_50x50.jpg")); // NOI18N
        geri_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102), 4));
        geri_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_butonu2ActionPerformed(evt);
            }
        });
        jPanel2.add(geri_butonu2);
        geri_butonu2.setBounds(1280, 30, 60, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("                BİLGİLERİMİ GÜNCELLE EKRANI");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255), 4));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(500, 40, 390, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel1.setLayout(null);

        guncelleMail_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleMail_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleMail_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleMail_alani);
        guncelleMail_alani.setBounds(700, 80, 200, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 51, 255));
        jLabel15.setText("        Mail Adresi");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(420, 80, 200, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 51, 255));
        jLabel17.setText("                 Adres");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 310, 190, 90);

        guncelleCep_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleCep_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleCep_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleCep_alani);
        guncelleCep_alani.setBounds(700, 200, 200, 40);

        guncelleParola_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleParola_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleParola_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleParola_alani);
        guncelleParola_alani.setBounds(210, 360, 170, 50);

        guncelleAdres_alani.setColumns(20);
        guncelleAdres_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleAdres_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleAdres_alani.setRows(5);
        guncelleAdres_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jScrollPane1.setViewportView(guncelleAdres_alani);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(700, 310, 210, 90);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 51, 255));
        jLabel16.setText("    Cep Telefon Numarası");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(420, 180, 200, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 255));
        jLabel13.setText("         Parola");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 370, 160, 40);

        guncelleSoyad_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleSoyad_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleSoyad_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleSoyad_alani);
        guncelleSoyad_alani.setBounds(210, 270, 170, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 255));
        jLabel12.setText("         Soyad");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 270, 160, 40);

        guncelleAd_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleAd_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleAd_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleAd_alani);
        guncelleAd_alani.setBounds(210, 190, 170, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 51, 255));
        jLabel11.setText("            Ad");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 180, 160, 40);

        guncelleTc_alani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        guncelleTc_alani.setForeground(new java.awt.Color(255, 0, 0));
        guncelleTc_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));
        jPanel1.add(guncelleTc_alani);
        guncelleTc_alani.setBounds(200, 80, 170, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 255));
        jLabel10.setText("     Tc Kimlik No");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 80, 159, 50);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(220, 120, 980, 440);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 4));

        Iptal_butonu.setBackground(new java.awt.Color(153, 255, 255));
        Iptal_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Iptal_butonu.setForeground(new java.awt.Color(255, 0, 0));
        Iptal_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\cancel_50x50.jpg")); // NOI18N
        Iptal_butonu.setText("İptal");
        Iptal_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 4));
        Iptal_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iptal_butonuActionPerformed(evt);
            }
        });

        bilgiGuncelle_butonu.setBackground(new java.awt.Color(153, 255, 255));
        bilgiGuncelle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilgiGuncelle_butonu.setForeground(new java.awt.Color(255, 0, 0));
        bilgiGuncelle_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\191-1918674_colour-change-icon-hd-png-download_50x50.jpg")); // NOI18N
        bilgiGuncelle_butonu.setText("Güncelle");
        bilgiGuncelle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 4));
        bilgiGuncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiGuncelle_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(bilgiGuncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(Iptal_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iptal_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilgiGuncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(230, 580, 970, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_butonu2ActionPerformed
        // TODO add your handling code here:
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
    }//GEN-LAST:event_geri_butonu2ActionPerformed

    private void Iptal_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iptal_butonuActionPerformed
        // TODO add your handling code here:
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
    }//GEN-LAST:event_Iptal_butonuActionPerformed

    private void bilgiGuncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiGuncelle_butonuActionPerformed
        // TODO add your handling code here:
        
        String tc = guncelleTc_alani.getText();
        String sifre = guncelleParola_alani.getText();
        String ad = guncelleAd_alani.getText();
        String soyad = guncelleSoyad_alani.getText();
        String mail = guncelleMail_alani.getText();
        String cepTel = guncelleCep_alani.getText();
        String adres = guncelleAdres_alani.getText();
        boolean durum = yonetici.bilgiGuncelle(ad, soyad,tc,sifre,mail, cepTel, adres, id);
        YardimciMethotlar.onay("eminim");
        if(durum){
            YardimciMethotlar.mesajGoster("basarili");
        }
        else{
            YardimciMethotlar.mesajGoster("hata");
        }
    }//GEN-LAST:event_bilgiGuncelle_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiBilgileriGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iptal_butonu;
    private javax.swing.JButton bilgiGuncelle_butonu;
    private javax.swing.JButton geri_butonu2;
    private javax.swing.JTextField guncelleAd_alani;
    private javax.swing.JTextArea guncelleAdres_alani;
    private javax.swing.JTextField guncelleCep_alani;
    private javax.swing.JTextField guncelleMail_alani;
    private javax.swing.JTextField guncelleParola_alani;
    private javax.swing.JTextField guncelleSoyad_alani;
    private javax.swing.JTextField guncelleTc_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
