/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.User;
import com.irem.models.Yoneticiler;

/**
 *
 * @author İREM SAMUR
 */
public class YoneticiAnaEkrani extends javax.swing.JFrame {
    private static Yoneticiler yonetici = new Yoneticiler();
    User user = new Yoneticiler();//polimorfizim uyguladık
    private static String yoneticiAdi;
    private static String yoneticiSoyadi;
    private static String yoneticiIsim;
    private static int id;
    private static String tc;
    private static String yoneticiParola;
    private static String mail;
    private static String adres;
    private static String cinsiyet;
    private static String cepTel;

    /**
     * Creates new form YoneticiAnaEkrani
     */
    public YoneticiAnaEkrani(Yoneticiler yonetici) {
        initComponents();
        yoneticiAdi = yonetici.getAd();
        yoneticiSoyadi = yonetici.getSoyad();
        yoneticiIsim = yoneticiAdi+" "+yoneticiSoyadi;
        user.girisMesajiYaz(yoneticiIsim);//polimorfizim sayesinde üst classın user'ın methodunu resepsiyonist classında override ederek
        //üst classdan oluşturulan nesne ile kullandık
        id = yonetici.getId();
        tc = yonetici.getTcno();
        yoneticiParola = yonetici.getParola();
        mail = yonetici.getMail_adresi();
        adres = yonetici.getAdres();
        cinsiyet = yonetici.getCinsiyet();
        cepTel = yonetici.getCeptel_no();
    }
    public YoneticiAnaEkrani(){
        initComponents();
        
    }
      public static String  tcNoDondur(){
        return tc;
        
    }
    public static int  idDondur(){
        return id;
        
    }
    public static String  yoneticiAdiDondur(){
        return yoneticiAdi;
        
    }
    public static String  yoneticiSoyadiDondur(){
        return yoneticiSoyadi;
        
    }
    public static String  parolaDondur(){
        return yoneticiParola;
        
    }
    public static String  mailDondur(){
        return mail;
        
    }
    public static String  adresDondur(){
        return adres;
        
    }
    public static String  cinsiyetDondur(){
        return cinsiyet;
        
    }
    public static String  ceptelDondur(){
        return cepTel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        resepsiyonistEkle_butonu = new javax.swing.JButton();
        bashekimGuncelle_butonu = new javax.swing.JButton();
        bashekimDegistir_butonu = new javax.swing.JButton();
        bashekimAta_butonu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bilgilerimiGosterItem = new javax.swing.JMenuItem();
        bilgiGuncelleItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cikisItem = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YÖNETİCİ ANA EKRANI");

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 255)));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\managers2.jpeg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 130, 208, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("                  HASTANE YÖNETİCİ EKRANI ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 40, 520, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 4));

        resepsiyonistEkle_butonu.setBackground(new java.awt.Color(255, 255, 255));
        resepsiyonistEkle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resepsiyonistEkle_butonu.setForeground(new java.awt.Color(0, 204, 102));
        resepsiyonistEkle_butonu.setText("Resepsiyonist Ekleme");
        resepsiyonistEkle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        resepsiyonistEkle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepsiyonistEkle_butonuActionPerformed(evt);
            }
        });

        bashekimGuncelle_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimGuncelle_butonu.setForeground(new java.awt.Color(0, 204, 102));
        bashekimGuncelle_butonu.setText("Başhekim Bilgi Güncelleme");
        bashekimGuncelle_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        bashekimGuncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashekimGuncelle_butonuActionPerformed(evt);
            }
        });

        bashekimDegistir_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimDegistir_butonu.setForeground(new java.awt.Color(0, 204, 102));
        bashekimDegistir_butonu.setText("Başhekim Değişimi");
        bashekimDegistir_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        bashekimDegistir_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashekimDegistir_butonuActionPerformed(evt);
            }
        });

        bashekimAta_butonu.setBackground(new java.awt.Color(255, 255, 255));
        bashekimAta_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bashekimAta_butonu.setForeground(new java.awt.Color(0, 204, 102));
        bashekimAta_butonu.setText("Başhekim Ataması");
        bashekimAta_butonu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        bashekimAta_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashekimAta_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(bashekimDegistir_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resepsiyonistEkle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(bashekimAta_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(bashekimGuncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bashekimGuncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bashekimAta_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resepsiyonistEkle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bashekimDegistir_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(420, 340, 600, 320);

        jMenu1.setText("Hesabım");

        bilgilerimiGosterItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        bilgilerimiGosterItem.setText("Bilgilerimi Göster");
        bilgilerimiGosterItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgilerimiGosterItemActionPerformed(evt);
            }
        });
        jMenu1.add(bilgilerimiGosterItem);

        bilgiGuncelleItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        bilgiGuncelleItem.setText("Bilgi Güncelle");
        bilgiGuncelleItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiGuncelleItemActionPerformed(evt);
            }
        });
        jMenu1.add(bilgiGuncelleItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Çıkış");

        cikisItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cikisItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\4700771_exit-power-off-icon-white-hd-png-download_50x50.jpg")); // NOI18N
        cikisItem.setText("Çıkış");
        cikisItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisItemActionPerformed(evt);
            }
        });
        jMenu2.add(cikisItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bashekimAta_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashekimAta_butonuActionPerformed
        // TODO add your handling code here:
        BashekimAtamaEkrani ataBashekim = new BashekimAtamaEkrani();
        ataBashekim.setVisible(true);
        dispose();
    }//GEN-LAST:event_bashekimAta_butonuActionPerformed

    private void bashekimGuncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashekimGuncelle_butonuActionPerformed
        // TODO add your handling code here:
        BashekimBilgiGuncelle guncelle = new BashekimBilgiGuncelle();
        guncelle.setVisible(true);
        dispose();
    }//GEN-LAST:event_bashekimGuncelle_butonuActionPerformed

    private void bilgilerimiGosterItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgilerimiGosterItemActionPerformed
        // TODO add your handling code here:
        YoneticiBilgileriniGoster bilgileriGoster = new YoneticiBilgileriniGoster();
        bilgileriGoster.setVisible(true);
        dispose();
    }//GEN-LAST:event_bilgilerimiGosterItemActionPerformed

    private void cikisItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisItemActionPerformed
        // TODO add your handling code here:
        AnaEkran ana = new AnaEkran();
        ana.setVisible(true);
        dispose();
    }//GEN-LAST:event_cikisItemActionPerformed

    private void bilgiGuncelleItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiGuncelleItemActionPerformed
        // TODO add your handling code here:
        YoneticiBilgileriGuncelle bilgiGuncelle = new YoneticiBilgileriGuncelle();
        bilgiGuncelle.setVisible(true);
        dispose();
    }//GEN-LAST:event_bilgiGuncelleItemActionPerformed

    private void bashekimDegistir_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashekimDegistir_butonuActionPerformed
        // TODO add your handling code here:
        BashekimDegistir degisim = new BashekimDegistir();
        degisim.setVisible(true);
        dispose();
    }//GEN-LAST:event_bashekimDegistir_butonuActionPerformed

    private void resepsiyonistEkle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepsiyonistEkle_butonuActionPerformed
        // TODO add your handling code here:
        ResepsiyonistEkle ekle = new ResepsiyonistEkle();
        ekle.setVisible(true);
        dispose();
    }//GEN-LAST:event_resepsiyonistEkle_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiAnaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiAnaEkrani(yonetici).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bashekimAta_butonu;
    private javax.swing.JButton bashekimDegistir_butonu;
    private javax.swing.JButton bashekimGuncelle_butonu;
    private javax.swing.JMenuItem bilgiGuncelleItem;
    private javax.swing.JMenuItem bilgilerimiGosterItem;
    private javax.swing.JMenuItem cikisItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resepsiyonistEkle_butonu;
    // End of variables declaration//GEN-END:variables
}
