/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.irem.jframes;

import com.irem.models.Yoneticiler;

/**
 *
 * @author İREM SAMUR
 */
public class YoneticiBilgileriniGoster extends javax.swing.JFrame {
    Yoneticiler yonetici = new Yoneticiler();
    private String ad;
    private String soyad;
    private String tc;
    private String parola;
    private String mail;
    private String cep;
    private String adres;
    private String cinsiyet;
    private int id;

    /**
     * Creates new form YoneticiBilgileriniGoster
     */
    public YoneticiBilgileriniGoster() {
        initComponents();
        id = YoneticiAnaEkrani.idDondur();
        tc = YoneticiAnaEkrani.tcNoDondur();
        yoneticiTc_etiketi.setText(tc);
        ad = YoneticiAnaEkrani.yoneticiAdiDondur();
        yoneticiAd_etiketi.setText(ad);
        soyad = YoneticiAnaEkrani.yoneticiSoyadiDondur();
        yoneticiSoyad_etiketi.setText(soyad);
        parola = yonetici.parolaGetir(id);
        yoneticiParola_etiketi.setText(parola);
        mail = YoneticiAnaEkrani.mailDondur();
        yoneticiMail_etiketi.setText(mail);
        cep = YoneticiAnaEkrani.ceptelDondur();
        yoneticiTel_etiketi.setText(cep);
        adres = YoneticiAnaEkrani.adresDondur();
        yoneticiAdres_etiketi.setText(adres);
        cinsiyet = YoneticiAnaEkrani.cinsiyetDondur();
        yoneticiCinsiyet_etiketi.setText(cinsiyet);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        geri_butonu2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yoneticiTel_etiketi = new javax.swing.JLabel();
        yoneticiMail_etiketi = new javax.swing.JLabel();
        yoneticiAdres_etiketi = new javax.swing.JLabel();
        yoneticiCinsiyet_etiketi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        yoneticiParola_etiketi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        yoneticiSoyad_etiketi = new javax.swing.JLabel();
        yoneticiAd_etiketi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        yoneticiTc_etiketi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YÖNETİCİ BİLGİLERİNİ GÖSTER");

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.setLayout(null);

        geri_butonu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\back-158491_1280_50x50.jpg")); // NOI18N
        geri_butonu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        geri_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_butonu2ActionPerformed(evt);
            }
        });
        jPanel2.add(geri_butonu2);
        geri_butonu2.setBounds(1270, 20, 60, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\İREM SAMUR\\Desktop\\javaProjects\\netbeansProjects\\HastaneOtomasyonuProjesi\\src\\com\\irem\\jframes\\image\\kisspng-computer-icons-printing-management-creative-busine-high-end-business-card-design-5adcaba622c989.0449529915244113021425_100x100.jpg")); // NOI18N
        jLabel1.setText("                             BİLGİLERİMİ GÖSTER");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(410, 60, 640, 100);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));
        jPanel1.setLayout(null);

        yoneticiTel_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiTel_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiTel_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiTel_etiketi);
        yoneticiTel_etiketi.setBounds(820, 200, 210, 30);

        yoneticiMail_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiMail_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiMail_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiMail_etiketi);
        yoneticiMail_etiketi.setBounds(820, 90, 210, 30);

        yoneticiAdres_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiAdres_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiAdres_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiAdres_etiketi);
        yoneticiAdres_etiketi.setBounds(820, 280, 220, 80);

        yoneticiCinsiyet_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiCinsiyet_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiCinsiyet_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiCinsiyet_etiketi);
        yoneticiCinsiyet_etiketi.setBounds(240, 360, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("         Cinsiyet");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 360, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("          Parola");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 290, 150, 30);

        yoneticiParola_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiParola_etiketi.setForeground(new java.awt.Color(255, 0, 0));
        yoneticiParola_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiParola_etiketi);
        yoneticiParola_etiketi.setBounds(240, 290, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("         Soyad");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 220, 150, 30);

        yoneticiSoyad_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiSoyad_etiketi.setForeground(new java.awt.Color(255, 0, 0));
        yoneticiSoyad_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiSoyad_etiketi);
        yoneticiSoyad_etiketi.setBounds(240, 220, 160, 30);

        yoneticiAd_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiAd_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiAd_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiAd_etiketi);
        yoneticiAd_etiketi.setBounds(240, 130, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("            Ad");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 130, 150, 30);

        yoneticiTc_etiketi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yoneticiTc_etiketi.setForeground(new java.awt.Color(255, 0, 102));
        yoneticiTc_etiketi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.add(yoneticiTc_etiketi);
        yoneticiTc_etiketi.setBounds(240, 60, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("      Tc Kimlik No");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 60, 159, 34);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("        Adres");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(550, 290, 210, 70);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("Cep Telefon Numarası");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(550, 200, 200, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("     Mail Adresi");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 4));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(550, 90, 200, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(80, 210, 1150, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_butonu2ActionPerformed
        // TODO add your handling code here:
        YoneticiAnaEkrani yonetici = new YoneticiAnaEkrani();
        yonetici.setVisible(true);
        dispose();
    }//GEN-LAST:event_geri_butonu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgileriniGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiBilgileriniGoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geri_butonu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel yoneticiAd_etiketi;
    private javax.swing.JLabel yoneticiAdres_etiketi;
    private javax.swing.JLabel yoneticiCinsiyet_etiketi;
    private javax.swing.JLabel yoneticiMail_etiketi;
    private javax.swing.JLabel yoneticiParola_etiketi;
    private javax.swing.JLabel yoneticiSoyad_etiketi;
    private javax.swing.JLabel yoneticiTc_etiketi;
    private javax.swing.JLabel yoneticiTel_etiketi;
    // End of variables declaration//GEN-END:variables
}
